import type { Task1Topic, Task2Topic } from './ielts-data';

type ArgumentSet = { position: string; first: string; second: string; example: string };

const a = (position: string, first: string, second: string, example: string): ArgumentSet => ({ position, first, second, example });

const argumentsById: Record<string, ArgumentSet> = {
  op1:a('a carefully designed hybrid model is preferable to either compulsory office attendance or permanent isolation','remote work converts commuting time into focused work and gives employees greater control over care responsibilities','fully remote teams can lose informal learning, so regular shared days and explicit communication routines remain necessary','a design firm can group collaborative meetings into two office days and reserve the remainder for uninterrupted production'),
  op2:a('practical literacy deserves a formal place in school without displacing core academic subjects','knowledge of budgeting, contracts and digital fraud gives young people immediate protection in adult life','academic disciplines develop reasoning that remains useful long after a particular practical procedure changes','a mathematics class can compare loan rates and build a realistic monthly budget'),
  op3:a('permanent collections should normally be free, while special exhibitions may reasonably charge','free entry broadens access to publicly funded heritage, especially for families who would otherwise stay away','total dependence on public money can weaken conservation budgets and the quality of temporary exhibitions','weekday entry can be free while memberships and touring shows subsidise preservation'),
  op4:a('non-essential flights should be reduced, but aviation policy cannot substitute for action on everyday car travel','rail alternatives and a frequent-flyer levy can remove high-emission journeys without preventing essential mobility','cars still dominate urban congestion and local air pollution because they are used in vastly greater numbers','companies can stop reimbursing flights where a rail journey takes under four hours'),
  op5:a('targeted discounts and better service are more effective than making every journey free','lower fares remove a genuine barrier for students, jobseekers and low-income workers','a zero fare cannot persuade drivers to switch if buses are infrequent, unsafe or overcrowded','a city can fund concession passes while adding reliable evening routes'),
  op6:a('age-appropriate controls and digital education are better than a blanket ban','unrestricted early use can displace sleep, exercise and face-to-face play','supervised devices also support navigation, family contact and accessible learning','parents can use an application whitelist while schools maintain phone-free lessons'),
  op7:a('students and society should share the cost of university through progressive funding','graduates often receive a private income premium and can fairly repay part of their tuition','society also gains qualified clinicians, teachers, research and informed civic participation','shortage occupations can receive grants while other graduates repay only after reaching an income threshold'),
  op8:a('private reporting is justified only where a clear public interest exists','investigating corruption, deception or a conflict of interest protects democratic accountability','health, relationships and children are normally irrelevant to public duties and exposure can cause irreversible harm','reporting an official’s hidden assets is defensible; photographing an actor’s child outside school is not'),
  op9:a('advertising needs strict rules rather than wholesale prohibition','commercial information can help new firms reach buyers and can finance free media','behavioural targeting, hidden sponsorship and child-directed marketing can manipulate vulnerable audiences','platforms can ban high-sugar food advertising to children and make paid promotion unmistakable'),
  op10:a('society should not rank disciplines solely by their immediate salary return','business education supports entrepreneurship, management and efficient allocation of resources','history trains people to test evidence, understand institutions and avoid repeating costly policy errors','an urban renewal team needs both a credible financial model and a knowledge of the community’s past'),
  di1:a('limited, supervised work experience should be integrated into study','undivided academic attention is essential where students must master a demanding body of knowledge','real workplaces reveal how theory, communication and judgement interact','a university can award credit for an eight-hour weekly placement supported by a trained mentor'),
  di2:a('essential services should come first, but a stable and transparent cultural budget is still justified','healthcare, housing and education protect survival and equal opportunity','the arts preserve shared memory, improve public space and sustain local employment','a government can set service minimums before allocating a small protected cultural fund'),
  di3:a('cooperation should be the classroom default, with bounded competition used as feedback','competition can motivate effort and teach children to recover from disappointment','collaboration develops listening, negotiation and shared responsibility, which more closely resemble adult work','a science project can receive a team mark alongside an individual reflection'),
  di4:a('incapacitation is necessary for serious violence, but rehabilitation prevents more ordinary reoffending','prison immediately protects the public and communicates social condemnation','education, treatment and employment change the conditions that often produce repeated crime','prisons can offer recognised trade certificates linked to employers who recruit after release'),
  di5:a('aid should follow need and likely impact while remaining transparent to local donors','domestic giving builds trust because contributors can see and monitor the results','extreme poverty and disaster cross borders, and the same donation may save far more lives elsewhere','a charity can publish a fixed split between evidence-led global aid and local programmes'),
  di6:a('digital access and printed deep reading should be combined according to purpose','paper reduces notifications and gives readers stable spatial cues','digital text is searchable, easily updated and accessible to people using assistive technology','students can preview electronic material and annotate a printed core chapter in seminars'),
  di7:a('cities should retain local shops alongside efficient large retailers','scale purchasing offers lower prices, broad choice and one-stop convenience','independent shops keep income locally and provide walkable services for residents without cars','planning rules can limit superstore size in historic centres and support shared delivery hubs'),
  di8:a('a broad lower-secondary curriculum should narrow gradually through later electives','early specialisation gives exceptional students time to reach a high level','teenage interests change, while broad study protects options and supports interdisciplinary thinking','schools can reserve most lessons for a common core and one third for specialist pathways'),
  di9:a('daily choices are personal, but governments are responsible for the environment in which choices occur','individuals decide what to eat, how to move and when to seek care','prices, advertising, food availability and street safety strongly shape what is realistically possible','clear food labels and safe walking routes expand healthy options without removing agency'),
  di10:a('structured interviews should be paired with anonymous work samples','interviews reveal communication, judgement and reactions to shared questions','practical tasks predict job performance more directly and reduce first-impression bias','an editor can mark an anonymised rewrite before attending a standardised interview'),
  ad1:a('tourism brings a net benefit when visitor numbers and environmental costs are actively managed','visitor spending supports livelihoods, heritage restoration and intercultural contact','unmanaged crowds raise rents, consume public space and create transport emissions','a historic city can require reservations and dedicate visitor fees to transit and resident housing'),
  ad2:a('the broad gains in access and choice outweigh manageable environmental costs','online markets serve remote communities, disabled customers and specialised needs','delivery, returns and excessive packaging create waste and weaken local high streets','consolidated delivery and reusable packaging can reduce the main external costs'),
  ad3:a('the academic and intercultural gains usually outweigh the risks where students receive adequate support','overseas study expands subject choice, independence and cross-cultural communication','high fees, isolation and brain drain can deepen inequality','paid placements and joint degrees can connect learning to both the host and home country'),
  ad4:a('population ageing is a challenge to redesign institutions, not evidence of social decline','older people contribute care, volunteering, expertise and consumer demand','pensions, healthcare and labour supply face genuine pressure when healthy life does not keep pace','flexible retirement and preventive medicine can extend healthy participation'),
  ad5:a('safety and mobility benefits can outweigh the risks only under transparent regulation','automated systems do not drive tired or intoxicated and can give disabled people independent mobility','software failures can scale rapidly, while cyber risk and liability remain unresolved','high-risk routes can retain human oversight and require public incident audits'),
  ad6:a('for focused knowledge work, the disadvantages of a fully open office are usually greater','shared space makes short exchanges easy and improves desk utilisation','noise, visual interruption and low privacy increase cognitive load and stress','quiet rooms, phone booths and designated collaboration days offer a better compromise'),
  ad7:a('global availability is useful, but long-term homogenisation weakens cultural and economic resilience','international supply chains offer reliable standards, lower prices and rapid access to innovation','local crafts and producers may disappear when a few global firms dominate shelf space','retailers can reserve space for local brands and make origin information visible'),
  ad8:a('a purposeful, time-limited gap year usually brings a net benefit','work, service and travel can clarify study choices and build maturity','unstructured time can break study habits and unpaid opportunities favour affluent families','universities can organise paid civic placements and guarantee deferred entry'),
  ad9:a('greater autonomy is positive, but cities must respond to loneliness and housing demand','living alone gives people control of space, time and career mobility','single households use more housing and energy per person and can weaken daily social contact','small homes with generous shared spaces can preserve privacy while enabling connection'),
  ad10:a('career mobility is positive only when social protection moves with the worker','changing jobs can improve pay, skill combinations and adaptation to technology','unstable income makes housing, care and long-term training harder to plan','portable benefit accounts can preserve insurance and leave across employers'),
  pr1:a('congestion requires reliable alternatives and pricing that reflects road scarcity','low-density planning and underpriced driving produce delays, pollution and unequal exposure','frequent public transport, safe active travel and peak road charges address both demand and alternatives','revenue from a central congestion zone can fund express buses from outer districts'),
  pr2:a('waste rises because disposable products are cheap while disposal costs are socialised','short product lives and excessive packaging increase landfill and household replacement spending','producer responsibility, repair rights and pay-as-you-throw systems change commercial incentives','electronics firms can take back devices and give longer warranties to replaceable batteries'),
  pr3:a('agricultural inefficiency, leaks and poor pricing are the main drivers of scarcity','water shortages threaten food production, hygiene and stability, hitting poorer households first','pipe repair, drip irrigation and protected basic-use allowances tackle the largest losses','a city can price essential use cheaply and charge progressively for pools and excessive irrigation'),
  pr4:a('childhood obesity reflects a food and activity environment, not simply weak parenting','aggressive marketing, calorie-dense products and unsafe streets make healthy routines difficult','advertising limits, nutritious school meals and active-travel routes reshape everyday defaults','schools can pair daily activity with a ban on oversized sugary drinks nearby'),
  pr5:a('rural decline follows the concentration of jobs, education and connectivity in cities','a shrinking workforce and tax base make schools, clinics and transport harder to sustain','broadband, regional colleges and incentives for distributed employment create viable local careers','public agencies can place back-office teams in smaller towns alongside vocational institutes'),
  pr6:a('youth offending requires early support and credible routes back into society','school exclusion, family strain and weak legal opportunities can reinforce one another','mentoring, family services, restorative justice and recognised training reduce repeat offending','a programme can combine a trade certificate with direct reparation to victims'),
  pr7:a('habitat loss and unsustainable production must be tackled together','fragmented ecosystems lose pollination, water regulation and resilience','ecological corridors, traceable supply chains and shared conservation income protect whole systems','wildlife crossings can reconnect habitat while farmers are paid to retain wetlands'),
  pr8:a('single-use plastic persists because its social cost is absent from its price','mixed plastics are difficult to recycle and fragments remain in water and food chains','deposit return, reuse standards and producer fees make redesign financially rational','standard bottles can be washed and circulated across several beverage brands'),
  pr9:a('housing pressure needs more well-located supply and protection from speculative vacancy','unaffordable rent produces long commutes, delayed families and shortages of essential workers','transit-oriented building, social housing and vacancy taxes address different parts of the market','large developments can be required to include permanently affordable homes'),
  pr10:a('sleep loss is driven by long hours, night-time screens and unstable shifts','fatigue damages judgement, productivity and transport safety','employers must limit late messaging and consecutive night work while individuals protect a regular shutdown routine','hospitals can shorten night rotations and provide safe transport after shifts'),
  tw1:a('differences in effort reflect goals, resources and status incentives; hard work is useful only when it remains directed and sustainable','clear rewards, family expectations and self-efficacy influence how much effort people invest','chronic overwork damages health and can allow visible busyness to replace effective results','teams can assess completed outcomes rather than hours shown online'),
  tw2:a('income pressure and organisational norms explain long hours, which are generally a negative development','low pay, insecurity and managerial example turn overtime into an unwritten expectation','output eventually falls while errors, illness and turnover increase','publishing team-level hours beside results exposes processes that consume time without adding value'),
  tw3:a('housing pressure, commuting and sensory overload drive stress; proximate services and public space offer the best relief','people still move to cities for employment, education and social opportunity','walkable neighbourhoods, quiet green areas and stable housing reduce structural stressors','placing childcare, clinics and groceries within walking distance removes repeated daily friction'),
  tw4:a('human welfare should guide science overall, while experts, citizens and governments should share priority-setting','public investment should address disease, environmental risk and infrastructure','exclusive focus on immediate applications would miss discoveries whose value cannot be predicted','independent panels can divide funds between social missions and investigator-led basic research'),
  tw5:a('locals see permanent displays as a one-time experience; rotating, co-created programmes can rebuild relevance','static content, ticket prices and working-hour schedules reduce repeat visits','evening access, resident-curated exhibitions and school partnerships create an ongoing relationship','a museum can build a neighbourhood history season around objects lent by local families'),
  tw6:a('influencers gain power through perceived intimacy and algorithmic reach; the effect is mixed but requires transparency','ordinary, frequent content creates a one-sided relationship that feels like friendship','hidden advertising and unrealistic images distort consumption and self-evaluation','platforms can make sponsorship labels prominent while schools teach commercial media literacy'),
  tw7:a('cheap replacement, difficult repair and upgrade marketing drive disposal, increasing resource pressure and hidden household costs','design and warranty policies often make repair less convenient than buying again','mining damage and waste exports shift the cost to communities far from consumers','durability labels and repair scores can reveal lifetime cost at the point of sale'),
  tw8:a('people worry because human activity has accelerated extinction; intervention should prioritise whole ecosystems','species are interdependent, so one loss can trigger an unpredictable ecological cascade','habitat restoration often protects water, climate resilience and local livelihoods together','wetland recovery can conserve birds and reduce flood risk at the same time'),
  tw9:a('screens, safety concerns and car-oriented streets reduce outdoor activity; daily environments must make movement easy','families turn to indoor entertainment when independent outdoor play feels unsafe','school activity, low-speed streets and nearby play space return exercise to ordinary routines','closing the road outside a school at dismissal can create a safe walking and play zone'),
  tw10:a('technology, restructuring and changing values make careers fluid; people need transferable skills, networks and financial resilience','automation changes tasks while employees increasingly seek meaning and flexibility','continuous learning and portable credentials are safer than predicting one supposedly future-proof job','an accountant who learns data visualisation can transfer domain expertise into analytics'),
};

export function task2Essay(topic: Task2Topic, version: 'A' | 'B') {
  const x = argumentsById[topic.id];
  if (version === 'A') {
    return [
      `The issue raised in this question is not a simple choice between two absolutes. In practice, its consequences depend on how the policy or behaviour is designed and whose interests are considered. My position is that ${x.position}. This judgement rests on both the immediate effects and the longer-term incentives that the change creates.`,
      `The first consideration is that ${x.first}. This matters because individual decisions accumulate: what appears to be a small convenience or cost for one person can alter access, productivity and opportunity across an entire community. When a system rewards the desired behaviour consistently, people do not have to rely on exceptional motivation. The result is therefore more durable than a short campaign or a purely moral appeal.`,
      `A second, equally important point is that ${x.second}. This qualification prevents an attractive idea from being applied too broadly. For instance, ${x.example}. The example shows that a workable response normally combines a clear principle with safeguards for people who would otherwise carry a disproportionate burden. It also makes outcomes easier to review and improve over time.`,
      `In conclusion, ${x.position}. The strongest approach is neither passive acceptance nor a blanket prohibition, but a proportionate framework that preserves the main benefit, limits foreseeable harm and remains responsive to evidence. Such a position is more likely to produce lasting public value than a solution based on a single slogan.`,
    ];
  }
  return [
    `Debate about this question often focuses on the most visible short-term effect. A better assessment asks how the change influences behaviour, fairness and capacity over time. I would argue that ${x.position}. Although the opposing concern deserves attention, it is not decisive when appropriate safeguards are available.`,
    `One persuasive reason is that ${x.first}. Beyond the direct benefit, this can widen participation and allow resources to be used where they have the greatest value. It may also remove a structural barrier that individual effort alone cannot overcome. Critics sometimes treat this outcome as uncertain, yet the mechanism is clear: incentives and available options shape repeated behaviour.`,
    `There is, nevertheless, a legitimate risk: ${x.second}. This is why implementation matters as much as intention. Consider how ${x.example}. A targeted arrangement of this kind is preferable to an unrestricted policy because it distinguishes essential needs from avoidable costs and creates a practical route for accountability.`,
    `Overall, the case is strongest for a measured version of the proposal. ${x.position}. Policymakers and institutions should define the intended outcome, monitor who benefits and who pays, and adjust the rules when evidence reveals unintended effects. This preserves the underlying advantage without pretending that every context is identical.`,
  ];
}

type ReportNotes = [string, string];
const reports: Record<string, ReportNotes> = {
  l1:['mobile subscriptions climbed dramatically and overtook fixed lines by the end, whereas landline growth was modest','the sharpest mobile expansion occurred after 1999, while the fixed-line series approached a plateau'],
  l2:['the United States remained the largest consumer despite a gradual decline, while China and the Middle East rose','China recorded the most substantial increase and was projected to approach the American level by 2030'],
  l3:['rail use fell for several decades before recovering strongly to finish at a record level','the trough occurred in the early 1980s, followed by more than twenty years of sustained growth'],
  l4:['science-museum attendance grew fastest and ended first, while the historical museum declined','the three figures were relatively close midway through the period before diverging markedly'],
  l5:['birth rates in both countries fluctuated but declined overall, with the American rate usually higher','China experienced sharper peaks and troughs around the 1950s before the two rates converged'],
  l6:['Companies A and B reduced their waste, whereas Company C increased its output and became the largest producer','A achieved the greatest absolute fall, while B rose briefly before entering a decline'],
  l7:['all three populations aged, and Japan was projected to move from last place to first','American and Swedish growth was gradual, but Japan was expected to accelerate sharply after 2030'],
  l8:['pollutant emissions fell substantially overall, led by a steep reduction in the electricity sector','transport was the only source to edge upwards and was close to industry by 2007'],
  l9:['in-person enquiries rose most dramatically to become the leading channel, while letters and emails declined','telephone enquiries were initially stable and then increased to rank second'],
  l10:['rural unemployment declined overall as the urban rate fluctuated upwards, and the two converged','the initial gap was the widest, whereas the urban figure showed two pronounced mid-year swings'],
  b1:['British households spent more in total and led especially in cars, while France was slightly higher for two goods','cars attracted the greatest spending in both countries and cameras produced the widest national gap'],
  b2:['men predominated in football and basketball, whereas women were more active in yoga and swimming','running showed the smallest gender gap and football the largest'],
  b3:['renewable generation increased in all four countries; Norway remained highest and Germany grew fastest','the United Kingdom stayed among the lowest despite almost doubling its share'],
  b4:['women dominated humanities and education, while men formed clear majorities in engineering and computing','business was the most balanced subject, whereas engineering displayed the strongest disparity'],
  b5:['visiting cafés was the most common habit in most cities, and instant coffee usually exceeded fresh coffee','Melbourne and Hobart led café attendance, while Adelaide recorded the lowest proportion'],
  b6:['vehicle ownership rose in every city; Seoul remained highest and Shanghai had the largest increase','cities starting from a lower base expanded faster, so the overall gap narrowed'],
  b7:['younger people strongly preferred gaming and socialising, while older adults favoured reading and gardening','television remained common across all ages and therefore showed the least variation'],
  b8:['earnings increased in every export category except gems and jewellery, with petroleum highest','textiles grew fastest in percentage terms despite remaining the smallest category by value'],
  b9:['public transport dominated in Tokyo and driving in New York, while London had a more balanced profile','walking and cycling were minority modes in all three cities'],
  b10:['the shares of children and working-age adults were projected to fall as the elderly population expanded','people aged 65 and over were expected to outnumber children by 2061'],
  p1:['the national energy mixes differed sharply, ranging from coal dominance to near-total reliance on hydropower','nuclear power was important in two countries, while newer renewable sources were still minor'],
  p2:['agriculture dominated water use in Africa, Asia and South America, but industry led in Europe and North America','domestic consumption was not the largest category in any region'],
  p3:['Asia contained the largest population share, whereas Europe and North America consumed disproportionate resources','food was the largest spending item worldwide and education the smallest'],
  p4:['housing dominated the Malaysian budget, while Japanese households spent most on other goods and services','transport and food were comparable across the two countries, and healthcare was smallest'],
  p5:['the share of commuters driving fell, while public transport and cycling together gained substantially','walking changed little and the transport mix became more balanced'],
  p6:['the share speaking only English declined as Chinese and Arabic became more common','Vietnamese and other languages were broadly stable, producing a more diverse school population'],
  p7:['Europe had the greatest total degradation, mainly from deforestation, while overgrazing dominated Oceania','North America was least affected and over-cultivation was its leading cause'],
  p8:['Australia became more dependent on coal, whereas France shifted decisively towards nuclear generation','hydropower changed little in both countries while French oil and gas contracted'],
  p9:['restaurant and convenience-food shares increased as fresh meat and vegetables declined','the household budget moved clearly from ingredients towards prepared services'],
  p10:['beaches remained the largest destination category but lost share as city and eco-tourism grew','mountain travel changed least and choices were more dispersed by 2020'],
  tb1:['London had the oldest and longest metro, Tokyo carried the most passengers, and Los Angeles was newest and shortest','system age did not correspond consistently with either route length or ridership'],
  tb2:['international enrolment rose in all four countries; Canada grew fastest and the United States remained largest','the United Kingdom expanded more moderately, while Australia hosted a high number relative to its population'],
  tb3:['leadership shifted from Western to Asian and Latin American cities as the size of the largest urban areas surged','New York led in 1950, but Tokyo, Delhi and Shanghai were far larger by the later dates'],
  tb4:['calling remained almost universal, while internet access and photography showed the fastest diffusion','texting stayed the second most common function and music use was comparatively limited'],
  tb5:['higher-income countries generally had longer life expectancy and greater calorie supply, though the link was imperfect','Canada led several indicators, while Peru and Zaire were markedly lower throughout'],
  tb6:['attendance increased everywhere and gains among girls reduced most gender gaps','high-performing countries changed little, while those with the lowest starting rates improved most'],
  tb7:['Sydney had the most stable temperatures, London had evenly distributed rainfall, and Dubai was hottest and driest','sunshine generally moved inversely to rainfall, although London showed milder seasonal variation'],
  tb8:['cinema attendance increased in every age group; the youngest remained highest and older viewers grew fastest','the age gap persisted but narrowed considerably by 2010'],
  tb9:['countries with the longest working weeks tended to provide the least paid leave, without a matching productivity lead','the Netherlands recorded the shortest week, while Japan recorded the longest'],
  tb10:['Hospital B combined the shortest wait and highest satisfaction but also the greatest operating cost','Hospital A was cheapest with the longest delay, while C occupied the middle ground'],
  pm1:['cement production is a multi-stage heat process, whereas concrete is made by directly mixing four ingredients','limestone and clay are crushed, blended, heated and ground before the finished cement is bagged'],
  pm2:['glass recycling forms a cycle from collection of used bottles to the return of new containers to shops','the material is sorted, washed, crushed and melted before being moulded with additional raw glass'],
  pm3:['salmon pass through three principal growth stages and migrate between habitats over roughly a decade','eggs hatch upstream, young fish move downstream, and adults mature at sea before returning to breed'],
  pm4:['roof water is collected, filtered and chemically treated before being supplied back to homes','the system has two broad phases—collection and purification—and operates as a community loop'],
  pm5:['brick manufacture is a linear seven-stage process from clay excavation to delivery','the clay is shaped, dried, fired at two temperatures, cooled, packaged and transported'],
  pm6:['the village changed from a fishing settlement into a tourist resort with extensive accommodation and leisure facilities','the harbour became a marina and activity zone, farmland gave way to hotels, and the main road was retained'],
  pm7:['the park became more accessible and family-oriented as paths, entrances and recreational facilities increased','some gardens were replaced by a playground and café, while the central water feature survived'],
  pm8:['the library shifted from book storage towards a multipurpose community space with digital and self-service areas','the newspaper section became a computer zone, the desk shrank, and children’s and refreshment spaces expanded'],
  pm9:['tourist infrastructure was added while the beach and much of the island vegetation were preserved','buildings were concentrated in the centre and west, leaving the eastern natural area largely intact'],
  pm10:['the proposal pedestrianises the core and redirects vehicles to a ring road and park-and-ride sites','shops become better connected, bus stops are consolidated, and the bridge and main landmarks remain'],
};

const cleanPrompt = (prompt: string) => prompt.replace(/^The (line graph|graph|bar chart|chart|pie charts|charts|table|tables|diagram|diagrams|maps|plans) /i, 'The visual ');
const metric = (topic: Task1Topic, index: number) => {
  const item = topic.facts[index];
  return item ? `${item.value}${item.unit || ''}` : 'the reported level';
};

export function task1Report(topic: Task1Topic, version: 'A' | 'B') {
  const [overview, detail] = reports[topic.id];
  if (version === 'A') {
    return [
      `${cleanPrompt(topic.prompt)} Overall, ${overview}.`,
      `Looking first at the principal features, ${detail}. The visual therefore presents a clear hierarchy rather than a set of evenly distributed values. One prominent measure reaches ${metric(topic,0)}, while another key point is recorded at ${metric(topic,1)}. These figures are most useful when read as evidence of the broader pattern rather than as isolated statistics.`,
      `The remaining information reinforces this contrast. Two further reference values are ${metric(topic,2)} and ${metric(topic,3)} respectively. Taken together, the data show that changes in rank, direction and relative scale are more significant than small movements within individual categories. No explanation for the pattern is supplied, so the report confines itself to the comparisons visible in the graphic.`,
    ];
  }
  return [
    `${cleanPrompt(topic.prompt)} In broad terms, ${overview}.`,
    `A useful way to organise the detail is to begin with the dominant pattern. ${detail}. The most conspicuous figure is ${metric(topic,0)}, compared with ${metric(topic,1)} for the next reference point. This establishes the main difference before the smaller categories or intermediate stages are considered.`,
    `Elsewhere, the visual records ${metric(topic,2)} and ${metric(topic,3)} at two relevant points. Although these numbers are less prominent, they confirm the direction described in the overview and clarify the relative size of the gap. Overall, the information is characterised by a small number of decisive contrasts rather than uniform movement across every item.`,
  ];
}
