export type GuideParagraph = {
  label: string;
  title: string;
  purpose: string;
  words: string;
  formula: string;
  steps: string[];
  sentenceFrames: string[];
  wordBank: string[];
  example: string;
  coachNote: string;
};

export type GuideCourse = {
  id: string;
  task: 'task1' | 'task2';
  name: string;
  en: string;
  accent: string;
  promise: string;
  duration: string;
  targetWords: string;
  coreRule: string;
  questionSignals: string[];
  examFlow: { time: string; action: string; output: string }[];
  blueprint: { part: string; words: string; job: string }[];
  paragraphs: GuideParagraph[];
  languageZones: { title: string; note: string; items: string[] }[];
  scoreFocus: { criterion: string; target: string; action: string }[];
  pitfalls: string[];
  checklist: string[];
  drills: string[];
};

const opinion: GuideCourse = {
  id: 'opinion', task: 'task2', name: '观点类', en: 'Opinion Essay', accent: '#ff745c',
  promise: '把“我同意”写成一条有立场、有因果、有边界的完整论证链。', duration: '40 MIN', targetWords: '270–290 WORDS',
  coreRule: '立场必须从开头到结尾保持一致。部分同意并不等于两边各写一半，而是承认一项合理之处后，明确哪一边更重要。',
  questionSignals: ['Do you agree or disagree?', 'To what extent do you agree or disagree?', 'Is this a positive or negative development?', 'Do the advantages outweigh the disadvantages?（需要权重判断时）'],
  examFlow: [
    { time: '00–03', action: '拆题', output: '圈出主题、限定词和任务词，写下一句立场。' },
    { time: '03–07', action: '搭论证', output: '选两个不重复的理由，各写一条“为什么—结果”。' },
    { time: '07–34', action: '成文', output: '按 4 段完成；每个主体段只证明一个中心。' },
    { time: '34–40', action: '检查', output: '核对立场、单复数、冠词、时态与句子边界。' },
  ],
  blueprint: [
    { part: 'P1 · Introduction', words: '40–50', job: '改写题目，并给出不可误读的立场。' },
    { part: 'P2 · Body 1', words: '85–95', job: '证明最强理由：主张 → 机制 → 结果 → 例证。' },
    { part: 'P3 · Body 2', words: '85–95', job: '证明次强理由，或先有限让步再反驳。' },
    { part: 'P4 · Conclusion', words: '30–40', job: '压缩立场与两条理由，不加入新观点。' },
  ],
  paragraphs: [
    {
      label: 'PARAGRAPH 01', title: '开头段：让考官十秒内看懂你的答案', purpose: '完成背景改写和 thesis。不要解释原因，不要写空泛的时代背景。', words: '40–50 words',
      formula: 'Paraphrase（1 句）＋ Position / Thesis（1 句）',
      steps: ['找出题目中的可替换成分：people / believe / important 等，保持原意而非逐词换同义词。', '选择立场：完全同意、基本同意、基本不同意或完全不同意。', '在 thesis 中预告两条理由，让后文结构可预测。'],
      sentenceFrames: ['It is often argued that [改写观点].', 'While I acknowledge that [有限让步], I largely agree that [主立场].', 'I strongly disagree with this view because it would [理由 1] and [理由 2].', 'This essay argues that [明确判断], primarily because [A] and [B].'],
      wordBank: ['contend 主张', 'maintain 认为', 'largely 基本上', 'to a limited extent 在有限程度上', 'be justified 有正当性', 'a more convincing view 更有说服力的观点'],
      example: 'It is often argued that public transport should be provided free of charge to all citizens. While lower fares would improve access, I largely disagree with a universal zero-fare policy because service quality and targeted support would produce greater social benefits.',
      coachNote: '“This essay will discuss …”没有错，但信息量低。Band 7+ 的 thesis 应直接给答案，并让主体段的两条理由露出来。',
    },
    {
      label: 'PARAGRAPH 02', title: '主体段一：把最强理由解释到不能再追问“为什么”', purpose: '提出第一核心理由，并完成至少两层因果解释。', words: '85–95 words',
      formula: 'Topic sentence → Why / mechanism → Consequence → Specific example → Link back',
      steps: ['主题句只写一个可争辩的中心，不要同时塞入三项好处。', '连续追问两次 why：为什么会发生？这又会带来什么结果？', '例子用具体场景证明机制，不必捏造研究机构和精确百分比。', '最后用一句评价把例子拉回题目中的 agree / disagree。'],
      sentenceFrames: ['The strongest reason for this position is that [核心理由].', 'This is because [第一层机制], which in turn [第二层结果].', 'For example, [具体群体/场景] can [行为], thereby [结果].', 'This makes [政策/趋势] not merely convenient but [评价].'],
      wordBank: ['yield measurable benefits 产生可衡量收益', 'remove a barrier 消除障碍', 'in turn 进而', 'thereby 从而', 'long-term capacity 长期能力', 'a tangible outcome 可见结果'],
      example: 'The strongest reason to prioritise service quality is that unreliable transport cannot persuade motorists to change their habits. Frequent and well-connected routes reduce both waiting time and uncertainty, which makes buses and trains a realistic alternative to driving. For example, late-shift workers are far more likely to leave their cars at home when night services are predictable. Investment in frequency therefore delivers a broader environmental benefit than free but infrequent journeys.',
      coachNote: '判断是否解释充分：遮住例子后，主题句与结论之间仍应有清晰的因果桥梁。若只有“because it is good”，论证尚未展开。',
    },
    {
      label: 'PARAGRAPH 03', title: '主体段二：增加一个新维度，而不是换词重复', purpose: '用不同评价标准建立第二条理由；部分同意时可在这里让步并限制其适用范围。', words: '85–95 words',
      formula: 'New angle / concession → Limit → Main claim → Explanation → Example',
      steps: ['检查与上一段是否属于不同维度，例如上一段写效率，本段写公平或长期影响。', '如需让步，只承认真实但有限的一点，并马上说明适用边界。', '使用 nevertheless / even so 等转折后，回到你的主立场。', '用比较词说明为什么这一理由权重更大。'],
      sentenceFrames: ['Admittedly, [对方合理点]. Nevertheless, this benefit is limited because [边界].', 'A further consideration is the question of [公平/成本/可持续性].', 'Even if [让步条件], it does not follow that [过度结论].', 'The latter concern carries greater weight because [权重理由].'],
      wordBank: ['admittedly 诚然', 'nevertheless 尽管如此', 'a disproportionate burden 不成比例的负担', 'fiscally sustainable 财政可持续的', 'outweigh 超过', 'be conditional on 取决于'],
      example: 'Admittedly, removing fares would benefit passengers who currently struggle with travel costs. Nevertheless, subsidising every journey would also transfer scarce public money to affluent commuters who need no assistance. A means-tested pass for students, job seekers and low-income workers would protect access while leaving more funding for new routes. This targeted approach is fairer because it directs support towards the people for whom price is a genuine barrier.',
      coachNote: '高分让步不是“有人不同意我”，而是准确说出对方在哪个条件下成立，再解释为什么它不足以推翻你的总体判断。',
    },
    {
      label: 'PARAGRAPH 04', title: '结尾段：做判断，不做复制粘贴', purpose: '用新的表达重申立场，并把两个理由压缩成一个综合判断。', words: '30–40 words',
      formula: 'Restated position ＋ Synthesis of reasons / condition',
      steps: ['不要引入新例子、解决方案或第三个理由。', '换掉开头的核心动词和句法结构，但不要改变立场强度。', '把两个理由合并为评价标准，例如“更公平且更有效”。'],
      sentenceFrames: ['In conclusion, I remain convinced that [立场].', 'Overall, [方案 A] is preferable to [方案 B] because it is both [评价 1] and [评价 2].', 'For these reasons, the claim that [题目观点] is ultimately unpersuasive.', 'The most defensible position is therefore to [判断], while [合理边界].'],
      wordBank: ['remain convinced 仍然确信', 'on balance 总体而言', 'ultimately 最终', 'a defensible position 可辩护的立场', 'preferable 更可取的', 'provided that 前提是'],
      example: 'In conclusion, free public transport may appear inclusive, but targeted fare support combined with reliable services is a more defensible policy because it is both fairer and more effective at reducing car use.',
      coachNote: '结论的价值在于“称重”。如果它只是机械重复开头，虽然不扣很多分，却浪费了展示清晰判断的最后机会。',
    },
  ],
  languageZones: [
    { title: '表达立场', note: '控制同意程度，避免模糊。', items: ['I strongly / largely / partly agree that …', 'I am not persuaded that …', 'This view is valid only to the extent that …', 'A more defensible position is that …'] },
    { title: '展开因果', note: '把观点变成论证链。', items: ['This is primarily because …', 'This, in turn, enables / prevents …', 'The immediate consequence is …', 'Over time, this would translate into …'] },
    { title: '举例与回扣', note: '例子服务于机制，而非替代解释。', items: ['A clear example can be seen in …', 'Consider, for instance, …', 'This illustrates why …', 'The example is significant because …'] },
    { title: '让步与反驳', note: '先给对方最强版本，再限制它。', items: ['Admittedly, …; nevertheless, …', 'Although this concern is legitimate, …', 'Even if this were true, it would not mean that …', 'The point has merit, but it is not decisive.'] },
  ],
  scoreFocus: [
    { criterion: 'Task Response', target: '立场清晰、回答完整、论点充分展开。', action: '每段结尾问：这一段如何直接证明我的答案？' },
    { criterion: 'Coherence & Cohesion', target: '段落中心单一，逻辑推进自然。', action: '用因果关系组织内容，不靠 Firstly / Secondly 堆连接词。' },
    { criterion: 'Lexical Resource', target: '词义准确、搭配自然、重复可控。', action: '优先记词组：pose a risk / yield benefits，而不是孤立“大词”。' },
    { criterion: 'Grammar Range & Accuracy', target: '复杂句有目的，简单句无硬伤。', action: '混合使用让步从句、定语从句与分词结果结构，并预留检查时间。' },
  ],
  pitfalls: ['立场在开头写 agree，结尾却变成 partly agree。', '一个主体段罗列三四个理由，每个理由都没有解释。', '为了“高级”使用不确定的生僻词，造成搭配或语义错误。', '例子包含虚构的精确研究数据，却没有说明因果机制。', '用 moreover 强行连接实际上相反或无关的句子。', '结论加入新解决方案，导致文章在最后突然改变方向。'],
  checklist: ['我是否完整回答了题目中的程度词或判断词？', 'thesis 是否一眼能看出立场和两个主体方向？', '每个主体段是否只有一个中心，并至少解释两层？', '例子是否具体且真正证明前面的机制？', '代词 this / they 是否有清晰指代？', '是否检查了主谓一致、可数名词、冠词和句号？'],
  drills: ['2 分钟 thesis 训练：同一题分别写完全同意与部分同意版本。', '因果链训练：把一个理由连续追问两次 why，再补一个真实场景。', '让步训练：用 Admittedly …; nevertheless … 写三组有限让步。', '压缩训练：把 90 词主体段缩成 35 词结论，不丢失判断。'],
};

const task2ScoreFocus: GuideCourse['scoreFocus'] = [
  { criterion: 'Task Response', target: '逐项回答任务，观点得到充分解释与支持。', action: '写完每段后，用题目的任务词追问：这一段究竟回答了什么？' },
  { criterion: 'Coherence & Cohesion', target: '段落中心清楚，信息按逻辑而非连接词推进。', action: '优先建立因果、对比和条件关系，再选择连接方式。' },
  { criterion: 'Lexical Resource', target: '词义准确、搭配自然，并能灵活改写题目。', action: '积累动词＋名词搭配，并检查“大词”是否真的适合语境。' },
  { criterion: 'Grammar Range & Accuracy', target: '句型有变化，复杂结构不牺牲准确度。', action: '长短句交替；重点检查从句边界、主谓一致和冠词。' },
];

const task1ScoreFocus: GuideCourse['scoreFocus'] = [
  { criterion: 'Task Achievement', target: 'Overview 清楚，关键特征选得准，数据支持充分。', action: '先用一句话说出图的“故事”，再决定哪些数字值得写。' },
  { criterion: 'Coherence & Cohesion', target: '数据按趋势、排名或阶段分组，而非逐项报数。', action: '每个细节段设置一个分组原则，并让比较发生在句内。' },
  { criterion: 'Lexical Resource', target: '趋势、程度、比较和占比表达准确多样。', action: '把词按功能成组记忆：rise / climb / surge，而不是随机替换。' },
  { criterion: 'Grammar Range & Accuracy', target: '时态、比较结构和数据单位稳定无误。', action: '先确定整图时间，再检查每句谓语与比较对象是否匹配。' },
];

const discussion: GuideCourse = {
  id:'discussion', task:'task2', name:'讨论类', en:'Discuss Both Views', accent:'#a9e6d1',
  promise:'公平解释两种观点，再用同一个评价标准做出自己的判断。', duration:'40 MIN', targetWords:'275–295 WORDS',
  coreRule:'Discuss both views 不是列出两边观点，而是解释每一边为什么有吸引力。个人意见必须明确，并最好通过共同标准比较两边。',
  questionSignals:['Discuss both views and give your own opinion.','Discuss both these views and give your opinion.','Some people think … while others believe …','Discuss both sides and state which you support.'],
  examFlow:[
    {time:'00–03',action:'拆成三项任务',output:'标记 View A、View B 与 your opinion，防止漏答。'},
    {time:'03–07',action:'建立比较标准',output:'用公平、效率、长期影响等同一把尺子衡量两边。'},
    {time:'07–34',action:'公平论证',output:'先写一边的合理逻辑，再写另一边并给判断。'},
    {time:'34–40',action:'反向检查',output:'两边篇幅是否合理？意见是否贯穿开头和结尾？'},
  ],
  blueprint:[
    {part:'P1 · Introduction',words:'45–55',job:'改写分歧，说明将讨论两边，并给出个人判断。'},
    {part:'P2 · View A',words:'85–95',job:'以支持者视角解释 A 的依据、收益及适用条件。'},
    {part:'P3 · View B + Opinion',words:'90–100',job:'解释 B，并用共同标准说明为何你更支持这一边。'},
    {part:'P4 · Conclusion',words:'30–40',job:'承认两边核心价值，重申比较后的最终结论。'},
  ],
  paragraphs:[
    {label:'PARAGRAPH 01',title:'开头段：把两种观点和你的判断同时摆上桌',purpose:'中立改写争议，并给出清晰路线与立场。',words:'45–55 words',formula:'Paraphrase the debate ＋ Both-view map ＋ Opinion',steps:['用 while / whereas 呈现真实分歧，不把任何一方写成荒谬观点。','把两种观点各压缩成一个准确短语。','明确你更支持哪边，或说明何种组合最合理。'],sentenceFrames:['Opinions are divided over whether [A] or [B].','While some favour [A] on the grounds that …, others advocate [B].','This essay will examine both positions; however, I am more persuaded by …','Although each view addresses a legitimate concern, [你的判断].'],wordBank:['opinions are divided 意见有分歧','advocate 支持','proponent 支持者','legitimate concern 合理顾虑','be more persuaded by 更信服于','competing priorities 竞争性目标'],example:'Opinions are divided over whether university students should focus exclusively on academic study or gain work experience at the same time. Although uninterrupted study is essential in demanding disciplines, I am more persuaded by structured work placements because they connect theory with professional judgement.',coachNote:'开头不用承诺“公平讨论”就结束；最后半句必须告诉考官你比较后的答案。'},
    {label:'PARAGRAPH 02',title:'主体段一：站在 View A 最强支持者的角度解释',purpose:'说明第一种观点依赖什么逻辑、在什么条件下成立，以及它的边界。',words:'85–95 words',formula:'View A → Rationale → Benefit → Example → Limitation',steps:['先写支持者真正关心的价值，例如深度、稳定或公平。','解释 A 如何带来该价值，不能只说 supporters think。','给一个能体现其优势的场景。','在段尾温和指出它并非适合所有情况，为比较做准备。'],sentenceFrames:['Supporters of the former view argue that …','This position rests on the assumption that …','Its principal merit is that …','This reasoning is strongest when …, although it is less convincing where …'],wordBank:['rest on an assumption 建立在假设上','academic depth 学术深度','undivided attention 全部注意力','cognitive load 认知负荷','be particularly valid for 尤其适用于','a notable limitation 明显局限'],example:'Supporters of full-time academic study argue that complex subjects require sustained concentration. Medical and engineering students, for instance, must master interconnected knowledge before applying it safely, and long working hours could fragment that learning. This position is especially persuasive during intensive examination or clinical periods. Its limitation, however, is that classroom mastery alone does not automatically develop communication, judgement or familiarity with workplace expectations.',coachNote:'讨论对方观点时不要夹带嘲讽。先把它写到最有说服力，后面的比较才有分量。'},
    {label:'PARAGRAPH 03',title:'主体段二：解释 View B，并完成真正的比较',purpose:'展开第二种观点，用与上一段相同的标准说明你的选择。',words:'90–100 words',formula:'View B → Mechanism → Evidence/example → Direct comparison → Opinion',steps:['主题句表明第二种观点的核心价值。','补全其作用机制和现实例子。','明确回到共同标准：谁覆盖更广、影响更久、风险更小？','用一句比较判断而不是只写 I agree。'],sentenceFrames:['Those who favour the latter approach point out that …','Exposure to [场景] enables people to …','Compared with [A], this benefit is broader because …','For this reason, I consider [B] the more effective approach, provided that …'],wordBank:['work-integrated learning 工学结合','transferable skill 可迁移技能','professional judgement 职业判断','bridge the gap 弥合差距','broader in scope 覆盖更广','provided that 前提是'],example:'By contrast, supervised work experience exposes students to deadlines, collaboration and professional feedback. A short placement can reveal why a classroom principle matters and help a student test whether a career suits them before graduation. Compared with academic study alone, this combination develops a broader range of capabilities. I therefore favour work-integrated learning, provided that placements are limited in hours, relevant to the course and supported by a trained mentor.',coachNote:'比较句是讨论类的灵魂。没有 compared with / more … because，文章容易变成两个互不相干的独立段。'},
    {label:'PARAGRAPH 04',title:'结尾段：用共同标准收束两边',purpose:'同时回收两种观点，并给出不含新信息的最终判断。',words:'30–40 words',formula:'Merit of A ＋ Merit of B ＋ Final preference / condition',steps:['各用一个短语概括两边价值。','明确你支持谁，或说明如何组合。','如有条件，只保留最关键的一项。'],sentenceFrames:['In conclusion, while [A] can [价值], [B] is more likely to [更重要结果].','Both approaches have merit; nevertheless, …','On balance, the latter view is more convincing because …','The best outcome would combine [A] with [B], with priority given to …'],wordBank:['on balance 权衡后','have merit 有道理','more compelling 更有说服力','not mutually exclusive 并非互斥','give priority to 优先考虑','a balanced arrangement 平衡安排'],example:'In conclusion, academic concentration protects subject depth, whereas supervised employment builds wider professional competence. The most effective arrangement is therefore to preserve rigorous study while integrating limited, course-relevant work experience.',coachNote:'结论应回答“比较之后怎样”，而不是再次详细解释两边。'},
  ],
  languageZones:[
    {title:'呈现观点',note:'保持中性，避免稻草人。',items:['Proponents of the former view contend that …','Those who favour the latter approach maintain that …','This perspective is grounded in …','The argument is particularly relevant when …']},
    {title:'解释依据',note:'说清观点为何合理。',items:['The reasoning behind this view is that …','This rests on the assumption that …','Its appeal lies in the fact that …','From the perspective of [group], …']},
    {title:'直接比较',note:'让两段真正发生联系。',items:['Compared with the former approach, …','The latter offers a more durable benefit because …','The first priority is important, but less decisive.','Measured against [standard], … is preferable.']},
    {title:'给出判断',note:'观点可以平衡，但不能含糊。',items:['I am more persuaded by …','While both positions have merit, …','A balanced approach need not treat them as mutually exclusive.','Priority should nevertheless be given to …']},
  ],
  scoreFocus:task2ScoreFocus,
  pitfalls:['只写两边“是什么”，没有解释“为什么”。','两边使用完全不同的评价标准，无法得出比较结论。','个人观点只在结尾出现，正文没有体现。','用 Some people think 重复开头所有句子。','为了看似平衡，把自己不支持的一边写得更长。','结论突然改成折中方案，前文却没有铺垫。'],
  checklist:['题目要求的 View A、View B、opinion 是否全部出现？','每一边是否都至少有一层机制解释？','两边是否用同一标准比较？','我支持的一边是否清楚且理由充分？','代词 former / latter 是否指向准确？','是否检查了观点动词后的 that 从句结构？'],
  drills:['为同一题分别写支持 A 与支持 B 的 thesis。','用“公平—效率—长期影响”三个标准各写一句比较。','把一个薄弱观点改写成最强版本，再指出适用边界。','在 90 秒内口头解释两边观点，禁止使用 good / bad。'],
};

const advantages: GuideCourse = {
  id:'advantages', task:'task2', name:'利弊类', en:'Advantages & Disadvantages', accent:'#d9ff67',
  promise:'不再罗列好处坏处，而是比较影响范围、持续时间与可逆性。', duration:'40 MIN', targetWords:'270–290 WORDS',
  coreRule:'先确认题目只要求 discuss advantages and disadvantages，还是进一步问 advantages outweigh disadvantages。后一种必须从开头就给权重判断。',
  questionSignals:['What are the advantages and disadvantages?','Do the advantages outweigh the disadvantages?','Is this a positive or negative development?','What are the benefits and drawbacks of this trend?'],
  examFlow:[{time:'00–03',action:'识别任务强度',output:'圈出是否需要 outweigh / positive-negative 判断。'},{time:'03–07',action:'给影响称重',output:'为每项影响标记范围、时长、可逆性和受影响者。'},{time:'07–34',action:'一利一弊深挖',output:'每段选最重要的一项，用机制和例子展开。'},{time:'34–40',action:'核对权重',output:'开头、正文评价和结论是否指向同一判断？'}],
  blueprint:[{part:'P1 · Introduction',words:'40–50',job:'改写趋势；如题目要求，立即回答是否利大于弊。'},{part:'P2 · Advantages',words:'85–95',job:'写最大优势、受益对象、机制与长期价值。'},{part:'P3 · Disadvantages',words:'85–95',job:'写主要代价、风险边界，以及是否可以缓解。'},{part:'P4 · Conclusion',words:'30–40',job:'按范围、持续时间或可逆性做最终称重。'}],
  paragraphs:[
    {label:'PARAGRAPH 01',title:'开头段：先判断题目要“列举”还是要“称重”',purpose:'准确改写趋势，并说明文章范围；需要 outweigh 时必须亮明判断。',words:'40–50 words',formula:'Trend paraphrase ＋ Scope ＋ Weight judgement (if required)',steps:['识别趋势主体、变化和受影响对象。','不用 dramatic / controversial 等题目未提供的评价词。','若有 outweigh，写清总体利大于弊或相反，并预告标准。'],sentenceFrames:['The growing tendency for [trend] has created both opportunities and concerns.','This development offers clear benefits, particularly in relation to …','Although [drawback] is significant, I believe the advantages are greater because …','On balance, this is a positive development, provided that …'],wordBank:['growing tendency 日益增长的趋势','bring about 带来','far-reaching effect 深远影响','on balance 总体而言','outweigh 超过','be contingent on 取决于'],example:'The growing use of artificial intelligence in education offers faster, more personalised support but also creates risks of dependency and inaccurate feedback. On balance, its advantages are greater, provided that teachers retain control over assessment and students learn to verify automated responses.',coachNote:'题目只问 advantages and disadvantages 时不强制判断；但如果问 outweigh，漏掉明确答案会直接影响 Task Response。'},
    {label:'PARAGRAPH 02',title:'主体段一：把优势写成“谁因此得到什么”',purpose:'说明最大收益的受益者、机制、范围与持续时间。',words:'85–95 words',formula:'Benefit → Beneficiary → Mechanism → Wider/long-term result → Example',steps:['选择一个能覆盖较多人或持续较久的优势。','指出直接受益者，避免笼统的 society。','解释便利如何进一步转化为学习、收入、健康等结果。','用具体场景证明，而不是再列第二个优势。'],sentenceFrames:['The most immediate benefit is that …','For [group], this lowers the barrier to …','More importantly, the gain extends beyond … because …','For instance, [scenario], allowing [beneficiary] to …'],wordBank:['lower the barrier to 降低门槛','enhance accessibility 提升可及性','generate spillover benefits 产生外溢收益','in the long run 长期而言','enable 使能够','a broad beneficiary group 广泛受益群体'],example:'The principal advantage of AI tutoring is its accessibility. Students who cannot afford private tuition can receive immediate explanations and practise at their own pace, which reduces the cost of basic academic support. The benefit also extends to teachers because routine questions can be handled outside class, leaving more time for discussion and individual feedback. In under-resourced schools, this combination can widen access without requiring a proportional increase in staffing.',coachNote:'“方便”通常只是第一层结果。继续追问：省下的时间、钱或精力最终创造了什么更重要的价值？'},
    {label:'PARAGRAPH 03',title:'主体段二：写清弊端的严重程度和可控边界',purpose:'解释主要风险由何产生、谁承担，以及它能否通过制度或行为缓解。',words:'85–95 words',formula:'Drawback → Cause → Harm → Boundary/mitigation → Weight',steps:['区分固有缺点与使用不当造成的问题。','说明损害的概率、范围或不可逆性。','如有可行缓解措施，只用一句说明，不要把文章写成 solution essay。','把弊端和上一段优势直接称重。'],sentenceFrames:['The principal drawback, however, is the risk that …','This problem arises when …','Its impact can be serious for …, since …','Nevertheless, the risk is manageable through … and is therefore less far-reaching than …'],wordBank:['unintended consequence 意外后果','overreliance 过度依赖','erode 削弱','misinformation 错误信息','mitigate 缓解','a reversible cost 可逆代价'],example:'The main drawback is that students may accept plausible but inaccurate answers or outsource the thinking process altogether. This risk is greatest when AI is used without teacher supervision or source checking. However, schools can require students to show working, compare sources and explain how a response was produced. Because these safeguards are practical, the danger is more manageable than the unequal access to support that the technology can help reduce.',coachNote:'提到解决办法的目的，是判断该弊端是否可逆、可控；不要在一段里列出三套政策。'},
    {label:'PARAGRAPH 04',title:'结尾段：明确告诉考官哪一边更重以及为什么',purpose:'用一个称重标准重申最终判断，不增加新利弊。',words:'30–40 words',formula:'Overall judgement ＋ Decisive weighing criteria ＋ Condition',steps:['先给最终判断。','点出决定性标准：覆盖范围、持续时间、严重性或可逆性。','若正文提过关键条件，可用 provided that 收束。'],sentenceFrames:['Overall, the advantages outweigh the disadvantages because …','The benefits are broader in scope and longer in duration than …','This remains a positive development, provided that …','The drawback is real, but both limited and reversible.'],wordBank:['broader in scope 范围更广','longer-lasting 更持久','irreversible 不可逆','manageable 可管理','decisive factor 决定因素','net benefit 净收益'],example:'Overall, AI-supported learning brings a wider and more lasting benefit than its manageable risks. It should therefore be viewed positively, provided that verification and teacher oversight remain central to its use.',coachNote:'“利大于弊，因为利很多”不是称重。必须说清是哪一个维度让它更重要。'},
  ],
  languageZones:[{title:'描述优势',note:'从便利推进到价值。',items:['One immediate benefit is that …','A more far-reaching advantage lies in …','This lowers the barrier to …','The gain extends beyond [A] to [B].']},{title:'描述弊端',note:'写风险来源与承担者。',items:['The principal drawback is the risk that …','This may place a burden on …','An unintended consequence is …','The harm is most acute when …']},{title:'评估程度',note:'为影响加上尺度。',items:['The effect is broad in scope but limited in duration.','This is a serious yet reversible cost.','The benefit accrues mainly to …','The risk can be substantially mitigated by …']},{title:'完成称重',note:'让 outweigh 有证据。',items:['The former consideration carries greater weight.','Its advantages are more substantial because …','The cost is narrower and more manageable.','The net social impact is therefore positive.']}],
  scoreFocus:task2ScoreFocus,
  pitfalls:['把优势和弊端各列三项，却没有一项解释充分。','题目问 outweigh，开头和结尾却不做判断。','同一影响换个说法分别写成优势和弊端。','使用 completely positive 等绝对判断，却忽略明显风险。','主体段变成解决方案清单。','比较时只看数量，不看影响的重要性。'],
  checklist:['我是否识别并回答了 outweigh / positive-negative？','每段是否只深入一个主要影响？','是否明确写了受益者或成本承担者？','是否用范围、持续时间或可逆性完成称重？','例子是否体现影响机制？','比较级和单复数是否准确？'],
  drills:['为四个利弊各标注 scope / duration / reversibility。','把三个浅层优势合并成一条完整因果链。','分别用 broader、longer-lasting、more reversible 写称重句。','用 40 词写一个带条件的正面发展结论。'],
};

const problem: GuideCourse = {
  id:'problem', task:'task2', name:'问题解决类', en:'Problem & Solution', accent:'#ffd36b',
  promise:'找到真正的根因，并让每个方案都有执行者、动作和作用机制。', duration:'40 MIN', targetWords:'275–295 WORDS',
  coreRule:'先分清题目问 causes、problems 还是两者之一。Cause 解释为何发生，problem 说明造成何种伤害；solution 必须精确对应前文，不可万能化。',
  questionSignals:['What problems does this cause, and what solutions can you suggest?','What are the causes of this problem and how can it be solved?','Why is this happening? What measures could be taken?','What problems are associated with this trend?'],
  examFlow:[{time:'00–03',action:'拆任务',output:'圈出 causes / problems / solutions，确认主体段职责。'},{time:'03–07',action:'画匹配箭头',output:'每个根因或问题后面写一个责任主体和针对动作。'},{time:'07–34',action:'写两条链',output:'问题链说明伤害，解决链说明如何切断该机制。'},{time:'34–40',action:'对应检查',output:'每个方案是否处理了正文提到的具体原因或后果？'}],
  blueprint:[{part:'P1 · Introduction',words:'40–50',job:'改写现象，准确说明将分析 causes/problems 与 solutions。'},{part:'P2 · Cause / Problem',words:'90–100',job:'写一至两个相关根因或后果，建立完整作用链。'},{part:'P3 · Solutions',words:'90–100',job:'写执行主体、具体动作、执行方式和预期效果。'},{part:'P4 · Conclusion',words:'30–40',job:'指出最关键干预点与可期待的总体结果。'}],
  paragraphs:[
    {label:'PARAGRAPH 01',title:'开头段：准确复述“症状”，不要抢先塞入所有答案',purpose:'界定现象和任务范围，并概括最核心的问题与解决方向。',words:'40–50 words',formula:'Problem paraphrase ＋ Main diagnosis ＋ Response direction',steps:['把题目现象中性改写，避免擅自扩大到全球或所有人。','确认是原因还是问题，不要混用 cause / consequence。','用一句路线句概括核心诊断与解决方向。'],sentenceFrames:['The growing prevalence of [phenomenon] has become a serious concern.','This trend is driven largely by … and results in …','The main difficulty lies in …','Addressing it will require coordinated action from …'],wordBank:['growing prevalence 日益普遍','underlying driver 深层驱动','consequence 后果','stem from 源于','be associated with 与…相关','coordinated action 协同行动'],example:'The growing volume of household waste places increasing pressure on urban services and the environment. This problem stems largely from disposable consumption and weak sorting systems, and it requires coordinated action by local authorities, retailers and residents.',coachNote:'若题目问 problems，不要把 P2 写成 why it happens；任务词错位会比语言小错更严重。'},
    {label:'PARAGRAPH 02',title:'主体段一：从根因走到可见伤害',purpose:'解释一个核心原因或问题如何逐步造成更严重后果。',words:'90–100 words',formula:'Root cause / problem → Mechanism → Immediate effect → Wider consequence → Example',steps:['选择能解释最多现象的根因，而不是最表面的症状。','用 because / when / as a result 补齐中间机制。','指出具体承担者或环境后果。','若写两个问题，确保它们属于同一条逻辑链。'],sentenceFrames:['The primary cause can be traced to …','When [condition], people / firms tend to …','The immediate consequence is …, which subsequently …','This is particularly evident in …'],wordBank:['underlying incentive 深层激励','single-use packaging 一次性包装','place strain on 对…造成压力','landfill capacity 填埋容量','contaminate 污染','compound the problem 加剧问题'],example:'A major driver is the low apparent cost of disposable packaging. When producers are not responsible for collection, single-use materials remain cheaper than reusable alternatives and consumers have little reason to change. The resulting waste strains municipal collection budgets and fills landfill sites, while contaminated recycling is often rejected. In densely populated cities, this combination raises public costs and increases pollution beyond the neighbourhood in which the waste was created.',coachNote:'好的问题段会让解决方案几乎“自己出现”：如果根因是价格激励，后文就该调整责任与价格，而非只做宣传。'},
    {label:'PARAGRAPH 03',title:'主体段二：方案必须写出“谁、做什么、怎么起作用”',purpose:'提出与前文一一对应、可实施并能解释效果的措施。',words:'90–100 words',formula:'Actor → Specific measure → Implementation → Mechanism → Expected result',steps:['先确定最有能力行动的主体：政府、学校、企业或个人。','使用可操作动词：require、subsidise、restrict、provide。','说明执行方式和遵守机制。','最后明确方案切断了前文哪条因果链。'],sentenceFrames:['A targeted response would be for [actor] to [action].','This could be implemented through …','By making [behaviour] more / less costly, the measure would …','In parallel, [second actor] should …, thereby …'],wordBank:['targeted intervention 针对性干预','extended producer responsibility 生产者延伸责任','deposit-return scheme 押金返还制度','enforcement mechanism 执行机制','incentivise 激励','address the root cause 处理根因'],example:'Local authorities should require producers to finance the recovery of the packaging they place on the market. A deposit-return scheme could charge consumers a small refundable amount and provide convenient collection points in supermarkets. This would give both firms and households a financial reason to reduce contamination and recover materials. In parallel, standardised labels should show exactly how each item is sorted, addressing the confusion that causes recyclable waste to be discarded.',coachNote:'“政府应该提高意识”太空。至少补全渠道、对象和行为变化：通过什么措施，让谁做出什么不同选择？'},
    {label:'PARAGRAPH 04',title:'结尾段：指出最关键的杠杆点',purpose:'压缩问题诊断与方案，并强调最有效的干预机制。',words:'30–40 words',formula:'Root problem ＋ Most effective response ＋ Expected outcome',steps:['用一个短语概括根因或核心伤害。','点名最有力的主体和行动。','写预期改善，不作“彻底消除”等过度承诺。'],sentenceFrames:['In conclusion, the problem is rooted primarily in …','The most effective response is to …','Together, these measures would reduce … by …','Lasting improvement depends on changing the incentives that …'],wordBank:['lasting improvement 持久改善','depend on 取决于','reduce at source 从源头减少','shared responsibility 共同责任','durable response 持久对策','substantially 大幅度地'],example:'In conclusion, excessive waste is rooted in weak producer responsibility and confusing collection. Financial recovery obligations and clear sorting systems would reduce waste at source and make recycling substantially more effective.',coachNote:'不要承诺 solve the problem completely。现实、有限但可解释的结果更可信。'},
  ],
  languageZones:[{title:'诊断原因',note:'从表面现象深入。',items:['This can be traced primarily to …','An underlying driver is …','The problem is reinforced by …','This creates an incentive for …']},{title:'说明后果',note:'建立影响链。',items:['The immediate consequence is …','This places considerable strain on …','Over time, the problem can undermine …','The effects are felt most acutely by …']},{title:'提出方案',note:'明确执行者与动作。',items:['A targeted response would be for … to …','Authorities could require / subsidise / restrict …','This should be implemented through …','Responsibility should be shared, but not diffused.']},{title:'解释作用',note:'说明方案如何有效。',items:['This would address the root cause by …','By changing the incentive to …','The measure would make it easier for …','This would prevent rather than merely remedy …']}],
  scoreFocus:task2ScoreFocus,
  pitfalls:['把原因、问题和后果混为同一个概念。','方案与前文问题没有对应关系。','每个方案只有 should，没有执行方式。','把所有责任推给个人，却不考虑制度激励。','主体段写成许多短小列表，没有机制解释。','用 raise awareness 代替具体措施。'],
  checklist:['题目究竟问 causes、problems 还是两者？','每个问题是否写清受影响者与后果？','每个方案是否有明确执行主体？','是否说明措施如何切断前文机制？','方案是否现实且不过度承诺？','cause / lead to / result in 的语法是否正确？'],
  drills:['为五个常见问题分别写 actor-action-mechanism。','把 raise awareness 改成三项具体可执行措施。','画两条 Problem → Cause → Solution 匹配链。','用 90 词只展开一个根因，禁止列第二个。'],
};

const twoPart: GuideCourse = {
  id:'two-part', task:'task2', name:'双问题类', en:'Two-part Question', accent:'#cbbcff',
  promise:'把两个问句拆成两项明确任务，并让答案在篇幅和逻辑上精准对齐。', duration:'40 MIN', targetWords:'270–295 WORDS',
  coreRule:'双问题类没有固定内容关系：可能是 why＋positive/negative，也可能是 causes＋effects。唯一稳定原则是 thesis 同时给出两个简短答案，两个主体段一段对应一问。',
  questionSignals:['Why is this the case? Is it a positive or negative development?','What are the reasons for this? What effects does it have?','Why does this happen? What should be done?','What factors cause this, and who should be responsible?'],
  examFlow:[{time:'00–03',action:'给问题编号',output:'在题面标 Q1 / Q2，圈出各自任务动词。'},{time:'03–07',action:'各写一句答案',output:'先写两句最短答案，再为每句补机制和例子。'},{time:'07–34',action:'一段一问',output:'P2 回答 Q1，P3 回答 Q2；复杂一问可稍长。'},{time:'34–40',action:'双向核对',output:'thesis 与结论是否都同时回收两个答案？'}],
  blueprint:[{part:'P1 · Introduction',words:'45–55',job:'改写现象，并用一句或两句分别回答 Q1 与 Q2。'},{part:'P2 · Answer Q1',words:'90–100',job:'针对第一问选择正确论证模式，完成解释与例证。'},{part:'P3 · Answer Q2',words:'90–100',job:'切换到第二问所需逻辑，给出独立且完整答案。'},{part:'P4 · Conclusion',words:'30–40',job:'把两项答案合并成一个总判断。'}],
  paragraphs:[
    {label:'PARAGRAPH 01',title:'开头段：把两个问句都变成可见答案',purpose:'改写共同背景，并为 Q1、Q2 各给一个简洁回应。',words:'45–55 words',formula:'Phenomenon paraphrase ＋ Answer to Q1 ＋ Answer to Q2',steps:['圈出两问的任务词，判断第一问要原因、第二问要评价还是方案。','改写两问共享的现象，不重复整道题。','用不同句法给出两个答案，避免 thesis 只答一半。'],sentenceFrames:['The growing tendency for [phenomenon] can be attributed mainly to …','This occurs for several reasons, the most important of which is …','Overall, I regard this as a positive / negative development because …','Although the trend is driven by …, its wider impact is …'],wordBank:['be attributed to 归因于','multifaceted 多层面的','driving factor 驱动因素','wider impact 更广泛影响','on the whole 总体上','be regarded as 被视为'],example:'More young adults are delaying home ownership, largely because property prices have risen faster than early-career incomes and stable employment arrives later. On the whole, this is a negative development because prolonged housing insecurity restricts both personal planning and economic independence.',coachNote:'好的 thesis 像“两格答案卡”：考官不需要猜哪半句在回答哪一问。'},
    {label:'PARAGRAPH 02',title:'主体段一：严格按照 Q1 的动词选择论证方式',purpose:'完整回答第一问，并用适合该任务的逻辑展开。',words:'90–100 words',formula:'Direct Q1 answer → Explanation → Consequence/example → Q1 link',steps:['若问 why，写原因与形成机制；若问 effects，写影响与承担者。','主题句直接复用 Q1 的逻辑，不要绕场。','解释至少两层，并给具体场景。','段尾用一句回到第一问，不提前回答 Q2。'],sentenceFrames:['The main reason for this shift is that …','A further factor is …, which makes it difficult for … to …','When [condition], individuals are more likely to …','These pressures together explain why …'],wordBank:['housing affordability 住房可负担性','income growth 收入增长','employment security 就业稳定性','postpone 推迟','financial threshold 财务门槛','explain the shift 解释变化'],example:'The principal cause is the widening gap between house prices and early-career earnings. Even diligent savers struggle to build a deposit when rent absorbs a large share of income, while temporary employment makes mortgage approval uncertain. In major cities, young professionals may therefore postpone buying despite having stable occupations and long-term plans. Later entry into secure work compounds this difficulty by shortening the period available for saving.',coachNote:'Q1 段只完成 Q1。提前把 positive/negative 评价塞进来，会让两段边界变模糊。'},
    {label:'PARAGRAPH 03',title:'主体段二：主动切换思维模式回答 Q2',purpose:'针对第二问独立建立评价、影响或解决链。',words:'90–100 words',formula:'Direct Q2 answer → Criterion / mechanism → Impact → Example → Judgement',steps:['重新读 Q2 的任务词，不沿用上一段的原因模式。','若问 positive/negative，选一个评价标准并完成权重判断。','若问 solution，写 actor-action-mechanism。','用明确判断句结束，确保 Q2 得到完整回应。'],sentenceFrames:['This should be regarded as a negative development because …','Its desirability depends largely on …','The most serious consequence is …','A practical response would be for [actor] to …, thereby …'],wordBank:['economic independence 经济独立','housing insecurity 住房不稳定','household formation 组建家庭','intergenerational inequality 代际不平等','net effect 净影响','carry greater weight 更重要'],example:'The wider effect is predominantly negative because insecure housing delays more than a single purchase. Adults who cannot predict their accommodation costs may postpone forming families, moving for work or investing in their communities. Although renting provides useful flexibility, that benefit is less significant when renting is not a choice but the result of exclusion from ownership. The loss of stability therefore carries greater social weight than the convenience of mobility.',coachNote:'Q2 如果是评价题，必须使用明确的评价语言和称重标准，不能只写“它有几个影响”。'},
    {label:'PARAGRAPH 04',title:'结尾段：用一条逻辑线合并两项答案',purpose:'同时重申 Q1 的解释和 Q2 的判断，让全文形成闭环。',words:'30–40 words',formula:'Q1 cause/finding ＋ Q2 judgement/response',steps:['Q1 用原因或核心发现压缩。','Q2 用判断或关键方案收束。','找出二者逻辑关系，用 because / while / therefore 合并。'],sentenceFrames:['In conclusion, this trend occurs mainly because …, and it is negative because …','Overall, [Q1 answer]; therefore, [Q2 answer].','While [main cause], the most appropriate response is …','The phenomenon is driven by …, with consequences that …'],wordBank:['in conclusion 总之','be driven by 由…驱动','therefore 因此','with consequences that 其后果是','overall judgement 总体判断','central explanation 核心解释'],example:'In conclusion, delayed home ownership is driven chiefly by the mismatch between housing costs and secure early-career income, and its overall effect is negative because it prolongs financial and personal uncertainty.',coachNote:'结论不是只复述你更喜欢的那一问。少回收一个答案，会暴露全文任务对齐不完整。'},
  ],
  languageZones:[{title:'回答原因问',note:'从因素走向机制。',items:['Several factors help to explain why …','The most influential of these is …','This makes people more likely to …','The explanation is as much [A] as [B].']},{title:'回答评价问',note:'明确方向和标准。',items:['On the whole, this is a negative development.','Its desirability depends largely on …','The net effect is positive because …','The latter consequence carries greater weight.']},{title:'回答影响问',note:'指明影响对象。',items:['The most immediate effect is …','This has wider implications for …','The burden falls disproportionately on …','Over time, it may translate into …']},{title:'回答方案问',note:'写出完整执行链。',items:['A practical response would be for … to …','This could be implemented through …','The measure would address … by …','Responsibility should lie primarily with …']}],
  scoreFocus:task2ScoreFocus,
  pitfalls:['只回答了更熟悉或更容易的一问。','thesis 写“本文将回答两个问题”，却不给答案。','Q1 和 Q2 在两个主体段中来回跳。','两问篇幅严重失衡。','把 why 误写成 problems，把 effects 误写成 solutions。','结论只回收一问。'],
  checklist:['题面上的两个问句是否都已编号？','thesis 是否包含两个简短答案？','P2 与 P3 是否一一对应 Q1 / Q2？','每段使用的论证模式是否匹配任务词？','两问篇幅是否基本平衡？','结论是否同时回收两项答案？'],
  drills:['随机选题，只用 60 秒写下 Q1 / Q2 两个短答案。','同一现象分别练 why、effects、solutions 三种展开。','把两个答案压缩进一个 35 词结论。','交换主体段顺序，检查逻辑是否仍清楚。'],
};

const line: GuideCourse = {
  id:'line', task:'task1', name:'折线图', en:'Line Graph', accent:'#ff745c',
  promise:'从多条线中抓出主趋势、拐点和交叉，而不是逐年报数。', duration:'20 MIN', targetWords:'170–190 WORDS',
  coreRule:'折线图考的是时间中的变化。Overview 先讲总体方向和最显著关系；细节段按趋势相似或相反分组，数字只为趋势提供证据。',
  questionSignals:['The line graph shows … from [year] to [year].','The graph compares changes in … over a period of …','Figures are given for / projected to …','The chart illustrates how … changed over time.'],
  examFlow:[{time:'00–02',action:'读轴与单位',output:'确认时间、单位、实线/预测值和系列数量。'},{time:'02–04',action:'给线分类',output:'标 ↑ ↓ ~ 波动，并圈峰值、谷值、交叉与反转。'},{time:'04–17',action:'四段成文',output:'Overview 不放细碎数字；细节段按趋势分组。'},{time:'17–20',action:'数据检查',output:'核对年份、单位、比较对象、时态和预测表达。'}],
  blueprint:[{part:'P1 · Introduction',words:'25–35',job:'改写图题，准确交代对象、地点、时间与单位。'},{part:'P2 · Overview',words:'35–45',job:'写两至三个最显著趋势、排名变化或交叉。'},{part:'P3 · Details 1',words:'50–60',job:'组织第一组相似趋势，给起点、终点与关键拐点。'},{part:'P4 · Details 2',words:'50–60',job:'写第二组/异常线，并完成有意义的跨系列比较。'}],
  paragraphs:[
    {label:'PARAGRAPH 01',title:'开头段：用一到两句准确交代图表边界',purpose:'说明比较对象、指标、时间和单位，不写原因或评价。',words:'25–35 words',formula:'Chart type ＋ What is measured ＋ Where/when ＋ Unit',steps:['读取标题、横轴、纵轴和单位。','选择 shows / compares / illustrates，避免机械替换每个词。','若后段为预测值，在开头用 includes projections 或时间范围交代。'],sentenceFrames:['The line graph compares changes in [measure] among [groups] between [year] and [year].','The graph illustrates how [indicator] changed over a [length]-year period.','Figures are expressed in [unit] and include projections to [year].','The chart provides information on [series] in [place] from [start] to [end].'],wordBank:['compare 比较','illustrate 展示','figure 数值','indicator 指标','be measured in 以…计量','projection 预测'],example:'The line graph compares the proportions of people aged 65 and over in the USA, Sweden and Japan between 1940 and 2040, with the final years representing projections.',coachNote:'Introduction 只需准确，不必炫技。不要写 The graph gives us information，也不要照抄整道题。'},
    {label:'PARAGRAPH 02',title:'Overview：先讲“线的故事”，暂时放下小数字',purpose:'概括主方向、最高最低变化和最明显的交叉或反转。',words:'35–45 words',formula:'General movement ＋ End ranking / contrast ＋ Major turning point',steps:['为每条线标方向：上升、下降、稳定、波动。','寻找共同趋势和异常者。','比较开头与结尾排名是否改变。','选择两到三个特征，通常不写精确数值。'],sentenceFrames:['Overall, all three figures increased, although at markedly different rates.','While X remained the largest for most of the period, Y is expected to overtake it by …','The most striking feature is the sharp reversal in …','By contrast, [series] followed a broadly stable / downward trajectory.'],wordBank:['overall 总体来看','trajectory 走势','overtake 超过','diverge 分化','converge 收敛','the most striking feature 最显著特征'],example:'Overall, the elderly population increased in all three countries. The USA and Sweden rose relatively steadily, whereas Japan remained lowest for most of the period before climbing sharply and becoming the highest by 2040.',coachNote:'读完 Overview，没看图的人也应该知道主故事。如果只写 fluctuate 或有很多变化，信息仍然不够。'},
    {label:'PARAGRAPH 03',title:'细节段一：把走势相近的线写在一起',purpose:'用关键年份和数字证明第一组趋势，并在句内比较。',words:'50–60 words',formula:'Starting comparison → Movement → Turning point → Ending comparison',steps:['按走势相似分组，而不是默认一条线一段。','优先选择起点、终点和一个改变方向的关键点。','用 while / compared with 让数字发生比较。','避免每个年份都写一次。'],sentenceFrames:['X stood at [value] in [year], compared with [value] for Y.','It then rose steadily / gradually to …','After remaining stable at around …, the figure climbed to …','The gap between the two series narrowed from … to …'],wordBank:['stand at 位于','rise steadily 稳步上升','edge up 小幅上升','remain stable 保持稳定','narrow the gap 缩小差距','respectively 分别'],example:'In 1940, the figures for the USA and Sweden were approximately 9% and 7% respectively. Both then increased, although the American proportion dipped slightly around 1980. By 2020, Sweden had moved ahead at about 20%, compared with roughly 18% in the USA.',coachNote:'respectively 只在顺序完全清楚时使用。数字要服务于比较，不能变成逗号串。'},
    {label:'PARAGRAPH 04',title:'细节段二：突出异常线、交叉点和预测变化',purpose:'完成其余系列，并说明它与第一组最有意义的关系。',words:'50–60 words',formula:'Exceptional start → Low/high point → Acceleration/reversal → Final rank',steps:['先说明该线为何与第一组不同。','选择谷值、峰值或加速点。','预测段使用 is expected/projected to。','在结尾完成最终排名或超越比较。'],sentenceFrames:['By contrast, X fell from … to a low of …','Growth was initially modest before accelerating after …','X is projected to surge to … by …','At this point, it will have overtaken both A and B.'],wordBank:['bottom out at 触底于','peak at 达峰值','accelerate 加速','surge 急升','be projected to 预计','a sharp upswing 快速上扬'],example:'Japan followed a contrasting path, falling from about 5% to roughly 3% before recovering slowly. Its proportion is then projected to accelerate after 2030 and reach around 27% in 2040, overtaking both Sweden and the USA.',coachNote:'历史数据用过去时，未来预测用 is projected/expected to。不要把整图都写成 will。'},
  ],
  languageZones:[{title:'上升',note:'根据速度与幅度选词。',items:['rise / increase / climb steadily','edge up slightly','grow substantially','surge / soar to …']},{title:'下降与稳定',note:'不要把所有下降都写 fall dramatically。',items:['decline gradually','dip slightly before recovering','fall back to …','level off / plateau at …']},{title:'变化结构',note:'描述拐点和幅度。',items:['after peaking at …','reach a low of …','a threefold increase','growth accelerated after …']},{title:'跨线比较',note:'强调关系变化。',items:['overtake / surpass …','the gap narrowed / widened','follow contrasting trajectories','remain consistently higher than …']}],
  scoreFocus:task1ScoreFocus,
  pitfalls:['逐年逐点报数，文章没有主次。','Overview 塞入太多精确数字。','每条线各写一段，错过跨系列比较。','实际数据和预测数据时态混乱。','把上升原因写进报告，加入图中不存在的信息。','数据点、单位或起止年份抄错。'],
  checklist:['开头是否写清对象、时间和单位？','Overview 是否包含总体方向与最显著关系？','细节段是否按趋势而非按线机械分组？','是否覆盖了峰值、谷值、交叉或反转中的关键项？','实际与预测时态是否区分？','数字和百分号是否核对？'],
  drills:['30 秒给每条线标 ↑ ↓ ~，口头说出两句 Overview。','把八个数据点删到只剩四个最有用的证据。','用同一组数据分别练 rise / climb / surge 的程度差异。','限时 5 分钟写一个无具体数字的高质量 Overview。'],
};

const bar: GuideCourse = {
  id:'bar', task:'task1', name:'柱状图', en:'Bar Chart', accent:'#a9e6d1',
  promise:'从密集柱形中快速建立排名、分组和倍数比较。', duration:'20 MIN', targetWords:'170–190 WORDS',
  coreRule:'柱状图通常是类别比较。先决定按国家、年份、性别还是高低组来组织，再选极值、相近项和异常值；不要从左到右逐柱朗读。',
  questionSignals:['The bar chart compares …','The chart shows the number / percentage of …','Figures are given for several categories / countries.','The bars illustrate changes between [year] and [year].'],
  examFlow:[{time:'00–02',action:'识别维度',output:'找类别、系列、时间和单位，确认是否有负值或堆叠。'},{time:'02–04',action:'排序分组',output:'圈最高最低，把相近柱归组并标异常值。'},{time:'04–17',action:'比较写作',output:'Overview 写极值和模式；每个细节句尽量包含比较。'},{time:'17–20',action:'核对数字',output:'检查类别、图例、单位、倍数与时态。'}],
  blueprint:[{part:'P1 · Introduction',words:'25–35',job:'改写比较对象、类别、时间和单位。'},{part:'P2 · Overview',words:'35–45',job:'写最高最低、总体模式和最突出差异。'},{part:'P3 · Details 1',words:'50–60',job:'写高值组、主要年份或第一系列，突出排序和倍数。'},{part:'P4 · Details 2',words:'50–60',job:'写低值组、第二系列与异常类别，补全对照。'}],
  paragraphs:[
    {label:'PARAGRAPH 01',title:'开头段：交代“谁在比什么”',purpose:'准确说明类别、系列、地点/年份及单位。',words:'25–35 words',formula:'Chart type ＋ Categories/series ＋ Measure ＋ Time/unit',steps:['区分横轴类别与图例系列。','确认数据是人数、比例、金额还是单位数。','静态图无需强行写 changed；多年份图需交代时间。'],sentenceFrames:['The bar chart compares [groups] in terms of [measure].','The chart shows the proportion of [people] who [activity] across [places].','Data are provided for [categories] in [years] and are measured in [unit].','The graph presents information on [indicator] by [group].'],wordBank:['in terms of 就…而言','proportion 比例','category 类别','by age group 按年龄组','be measured in 以…计','data are provided for 数据涵盖'],example:'The bar chart compares the proportions of residents in five Australian cities who bought fresh coffee, purchased instant coffee or visited a café during the previous four weeks.',coachNote:'不要把所有类别名称在开头再读一遍；概括为 five cities / three habits 即可。'},
    {label:'PARAGRAPH 02',title:'Overview：锁定冠军、垫底和一致模式',purpose:'概括极值、普遍规律和最明显例外，不逐项给数。',words:'35–45 words',formula:'Dominant category ＋ Lowest category ＋ Shared pattern / exception',steps:['找哪个系列在多数类别中领先。','找总体最低或差距最大者。','判断模式是否跨类别一致。','如有例外，优先写入 Overview。'],sentenceFrames:['Overall, X recorded the highest figures in most categories.','By contrast, Y was consistently the least common choice.','The pattern was broadly similar across all five cities.','One category stands out as the only exception to this trend.'],wordBank:['rank first 位居首位','record the highest figure 录得最高值','consistently 始终','dominant 占主导','exception 例外','broadly similar 大体相似'],example:'Overall, visiting cafés was the most common habit in four of the five cities, whereas buying fresh coffee was generally the least popular. Instant coffee exceeded fresh coffee everywhere, with Adelaide providing the only exception to café dominance.',coachNote:'Overview 不是“柱子有高有低”。必须写出谁高、谁低、模式是否一致。'},
    {label:'PARAGRAPH 03',title:'细节段一：把高值和相近项放在一个比较框架里',purpose:'通过排名、差距和相近值呈现第一组数据。',words:'50–60 words',formula:'Top group → Exact values → Similarities/differences → Rank',steps:['先选择高值城市/类别或第一年份。','一句中比较两到三个相关值。','相近值用 roughly / marginally；明显差距用 considerably。','避免重复 The figure for。'],sentenceFrames:['X recorded the highest figure, at approximately …','This was marginally higher than Y, at …','A and B posted broadly comparable figures of … and …','The value for X was roughly twice that for Y.'],wordBank:['outstrip 超过','marginally 略微','considerably 显著地','comparable 相近的','roughly double 约为两倍','stand at 位于'],example:'Café attendance was highest in Melbourne and Hobart, at about 64% and 63% respectively, followed closely by Sydney at just over 60%. Brisbane was lower at roughly 55%, while Adelaide recorded the smallest café figure, at just under half of residents.',coachNote:'倍数比较写 A was twice as high as B 或 A was twice the figure for B，避免 more than two times higher。'},
    {label:'PARAGRAPH 04',title:'细节段二：完成低值组与跨系列对照',purpose:'覆盖其余数据，并突出异常差距或唯一例外。',words:'50–60 words',formula:'Remaining series → Cross-category pattern → Exception → Final comparison',steps:['转向第二、第三系列或较低组。','先写跨所有类别的一致关系。','只给能证明关系的代表数字。','最后点出最小差距或异常值。'],sentenceFrames:['Instant coffee purchases exceeded fresh coffee in every city.','The disparity was most pronounced in …','Only in [category] were the two figures broadly comparable.','Elsewhere, figures ranged from … to …'],wordBank:['exceed 超过','range from … to … 范围为','disparity 差距','pronounced 明显的','elsewhere 其他地方','a narrow margin 小幅差距'],example:'Instant coffee purchases ranged from around 46% in Sydney to approximately 54% in Hobart and Brisbane, exceeding fresh coffee in every city. Fresh coffee peaked at about 44% in Sydney and Melbourne but fell to roughly one third in Brisbane and Adelaide.',coachNote:'每个细节段都应有一个分组逻辑。若句子顺序只跟着柱子从左到右走，结构通常可以更好。'},
  ],
  languageZones:[{title:'排名',note:'写极值和顺序。',items:['rank first / last','record the highest / lowest figure','be followed by …','stand out from the remaining categories']},{title:'倍数与差距',note:'用准确结构。',items:['be roughly twice the figure for …','exceed … by 15 percentage points','be marginally / considerably higher','show the widest disparity']},{title:'相近与范围',note:'合并数据。',items:['post broadly comparable figures','differ by only a narrow margin','range from … to …','cluster at around …']},{title:'模式与例外',note:'把多柱压缩成规律。',items:['a broadly consistent pattern','in every category except …','the only notable exception','show the reverse pattern']}],
  scoreFocus:task1ScoreFocus,
  pitfalls:['从左到右逐柱报数。','把百分点差写成百分比增长。','静态图错误使用 rose / fell。','Overview 没有最高、最低或总体模式。','twice higher 等倍数结构错误。','只比较同一类别内部，缺少跨类别分组。'],
  checklist:['开头是否写清类别、系列和单位？','Overview 是否指出极值与总体模式？','细节段是否有明确分组原则？','是否至少使用了排名、差距或倍数比较？','静态图是否避免变化动词？','所有数值是否对应正确图例？'],
  drills:['15 秒按高、中、低给所有柱分组。','用一句话合并三个相近数值。','分别用 percentage points 与 percent 写正确差异。','把五句逐柱描述压缩成两句比较。'],
};

const pie: GuideCourse = {
  id:'pie', task:'task1', name:'饼图', en:'Pie Chart', accent:'#d9ff67',
  promise:'把扇区转化成结构关系，清楚写出主导项、组合占比与结构迁移。', duration:'20 MIN', targetWords:'170–190 WORDS',
  coreRule:'饼图不是扇区清单。单饼看主导和小项组合；多饼先判断结构变得更集中还是更均衡、份额从何处转向何处。',
  questionSignals:['The pie chart shows how … is distributed.','The charts compare the proportions of …','The diagrams show the composition of … in [years/countries].','The charts illustrate expenditure by category.'],
  examFlow:[{time:'00–02',action:'确认总量',output:'每个饼是否各自为 100%，单位是百分比还是绝对值？'},{time:'02–04',action:'组合扇区',output:'圈最大最小，把小项或相近项组成有意义的组。'},{time:'04–17',action:'写结构变化',output:'Overview 先写主导与迁移，细节段比较组合份额。'},{time:'17–20',action:'检查算术',output:'核对加总、百分点变化、年份与类别颜色。'}],
  blueprint:[{part:'P1 · Introduction',words:'25–35',job:'改写主题、对象、地点/年份与比例单位。'},{part:'P2 · Overview',words:'35–45',job:'写主导类别、最小类别和集中度/结构变化。'},{part:'P3 · Details 1',words:'50–60',job:'写主要份额与组合占比，完成第一组饼图比较。'},{part:'P4 · Details 2',words:'50–60',job:'写小项和最大增减，用百分点说明结构迁移。'}],
  paragraphs:[
    {label:'PARAGRAPH 01',title:'开头段：说明这些圆在比较什么结构',purpose:'交代总体对象、类别、年份/地区，避免逐项抄扇区。',words:'25–35 words',formula:'Chart type ＋ Composition/distribution of what ＋ Groups/time',steps:['确认是支出、能源、人口还是用途构成。','多饼图概括数量和比较维度。','不要写饼图“changes”除非确有时间变化。'],sentenceFrames:['The pie charts compare the composition of [whole] in [groups/years].','The charts show how [total] was distributed among [number] categories.','The diagrams illustrate the proportions of [items] in [places].','Figures are expressed as percentages of the total.'],wordBank:['composition 构成','distribution 分布','proportion 比例','category 类别','of the total 占总量','be divided among 被分配到'],example:'The pie charts compare how average household expenditure in Japan and Malaysia was distributed among five categories in 2010.',coachNote:'composition / distribution 能准确概括饼图任务，比 give information about 更具体。'},
    {label:'PARAGRAPH 02',title:'Overview：判断结构是“集中、均衡”还是“发生迁移”',purpose:'概括主导类别、最小类别和不同饼之间的核心结构差异。',words:'35–45 words',formula:'Largest share ＋ Smallest share ＋ Concentration/change pattern',steps:['找每个饼第一大项和最小项。','判断相同类别是否仍占主导。','多年份图找最大百分点增减。','说明整体更集中、更分散或转向。'],sentenceFrames:['Overall, X accounted for the largest share in …, whereas Y dominated …','The smallest proportion in both charts was …','The distribution became noticeably more balanced over time.','The composition shifted away from [A] towards [B].'],wordBank:['account for 占','dominate 主导','combined share 合计份额','be concentrated in 集中于','more balanced 更均衡','shift away from 从…转移'],example:'Overall, housing represented the largest expense in Malaysia, while Japanese households spent most on other goods and services. Health care was the smallest category in both countries, and Malaysia’s budget was more concentrated in its two leading items.',coachNote:'Overview 可以比较结构，不需要强行写总体“上升下降”。饼图核心是份额关系。'},
    {label:'PARAGRAPH 03',title:'细节段一：用组合占比压缩主要扇区',purpose:'说明最大类别、第二大类别及合计份额，避免一项一句。',words:'50–60 words',formula:'Largest category → Runner-up → Combined share → Cross-chart contrast',steps:['选大项组，通常覆盖每个饼的前两项。','能加总时用 together / combined。','一句中并排比较不同饼的同类项目。','数字精确到图中可读程度即可。'],sentenceFrames:['X accounted for the largest share, at …','Together, A and B made up nearly two thirds of …','The corresponding figure for Y was …','X represented a substantially larger proportion in A than in B.'],wordBank:['constitute 构成','make up 占据','nearly two thirds 近三分之二','corresponding share 对应份额','substantially 显著地','the two leading items 两大项'],example:'Housing made up 34% of Malaysian expenditure, followed by food at 27%; together these categories represented just over three fifths of the budget. In Japan, by contrast, other goods and services ranked first at 29%, while housing accounted for a much smaller 21%.',coachNote:'组合前先确认同一饼的份额可以相加。不同国家的百分比不能直接加在一起。'},
    {label:'PARAGRAPH 04',title:'细节段二：写小项、差距和最大的结构变化',purpose:'覆盖其余类别，并用百分点准确表达份额差。',words:'50–60 words',formula:'Smaller categories → Similarity/difference → Percentage-point change → Final contrast',steps:['把多个小项合并写，而非逐个开句。','对同一类别跨饼比较。','份额从 20% 到 30% 是上升 10 percentage points。','用 no other category / the remainder 压缩信息。'],sentenceFrames:['No other category represented more than …','The shares for A and B were broadly comparable.','The proportion increased by [number] percentage points.','The remaining categories collectively accounted for …'],wordBank:['percentage point 百分点','the remainder 其余部分','collectively 合计','minor category 小类别','broadly comparable 大体相近','represent 构成'],example:'Transport and food took broadly similar shares in Japan, at 20% and 24%, compared with 10% and 27% in Malaysia. Health care remained the smallest item in both budgets, representing 6% in Japan and only 3% in Malaysia.',coachNote:'percentage points 描述两个份额之间的绝对差；percent 描述相对增幅，二者不要混用。'},
  ],
  languageZones:[{title:'份额',note:'替换单一 account for。',items:['account for / make up …','constitute / represent …','take the largest share','comprise almost half of …']},{title:'组合',note:'把小项和大项成组。',items:['a combined share of …','together make up …','collectively account for …','the remaining categories …']},{title:'结构变化',note:'写多饼的迁移。',items:['shift away from … towards …','become more evenly distributed','show greater concentration in …','gain / lose percentage points']},{title:'极值与限制',note:'突出主导和小项。',items:['dominate the overall mix','be the smallest component','no other category exceeds …','be twice the share of …']}],
  scoreFocus:task1ScoreFocus,
  pitfalls:['每个扇区各写一句，信息碎片化。','把不同饼图的百分比直接相加。','percentage points 和 percent 混淆。','只写最大项，忽略结构变化。','Overview 堆入所有数值。','使用人数增减语言描述份额变化。'],
  checklist:['每个饼是否各自为 100%？','Overview 是否写主导项与结构差异？','是否使用组合份额减少流水账？','百分点变化是否计算正确？','不同饼之间是否有直接比较？','类别名称和年份是否对应？'],
  drills:['十秒找出每个饼的 Top 2 与 Bottom 1。','用 together / collectively 合并三组扇区。','练习区分 10 percentage points 与 a 50% increase。','用两句写出从集中到均衡的结构迁移。'],
};

const table: GuideCourse = {
  id:'table', task:'task1', name:'表格', en:'Table', accent:'#ffd36b',
  promise:'横看对象、纵看指标，在密集单元格中选出真正值得报告的数据。', duration:'20 MIN', targetWords:'170–190 WORDS',
  coreRule:'表格没有图形替你突出重点，所以先横向找“谁多项领先”，再纵向找“哪个指标差距最大”。不同单位的列不能直接比较大小，只能比较排名或模式。',
  questionSignals:['The table shows / compares …','The table provides information about …','Data are given for [countries/categories] according to [indicators].','The figures show changes in … across [years].'],
  examFlow:[{time:'00–02',action:'读表头单位',output:'逐列确认单位、年份和是否包含总计/变化率。'},{time:'02–04',action:'横纵扫描',output:'横看领先对象，纵看极值和最大差距，圈异常单元格。'},{time:'04–17',action:'按故事分组',output:'每段只选 2–4 个关键数字支持一个模式。'},{time:'17–20',action:'单元格复核',output:'检查行列交叉、单位、排名与时态。'}],
  blueprint:[{part:'P1 · Introduction',words:'25–35',job:'说明表格对象、指标、时间及不同单位。'},{part:'P2 · Overview',words:'35–45',job:'写整体领先者、共同模式和差距最大的指标。'},{part:'P3 · Details 1',words:'50–60',job:'按对象比较高值组或第一组指标。'},{part:'P4 · Details 2',words:'50–60',job:'按指标覆盖其余对象，突出例外和相近值。'}],
  paragraphs:[
    {label:'PARAGRAPH 01',title:'开头段：准确概括行、列和时间',purpose:'说明比较对象与指标，必要时概括多种单位。',words:'25–35 words',formula:'Table ＋ Rows/groups ＋ Columns/indicators ＋ Time',steps:['识别行是对象还是指标。','把多个列标题概括为 performance indicators / demographic measures。','时间表格要写年份；静态表格不使用变化动词。'],sentenceFrames:['The table compares [groups] across [number] indicators.','The table provides data on [measures] in [places/years].','Information is given for [objects] in terms of [indicators].','Figures are presented in [units], depending on the measure.'],wordBank:['indicator 指标','measure 衡量项','in terms of 就…而言','provide data on 提供…数据','corresponding figure 对应数值','depending on 视…而定'],example:'The table compares four countries in terms of annual income, average life expectancy and daily calorie supply.',coachNote:'单位不同时，可以说 across three socioeconomic indicators，不必把美元、年和卡路里硬塞进一个长句。'},
    {label:'PARAGRAPH 02',title:'Overview：找到“多项领先者”和最强关联',purpose:'概括对象排名、共同模式、极端差距或唯一例外。',words:'35–45 words',formula:'Overall leader/laggard ＋ Cross-column pattern ＋ Exception/largest gap',steps:['横看每一行，找多项领先或垫底对象。','纵看每一列，判断排名是否相似。','找差距最大和最小的指标。','不写全部精确数字。'],sentenceFrames:['Overall, X led the table on most measures, while Y ranked last.','A broadly similar ranking can be seen across all three indicators.','The greatest variation occurred in …','This was the only measure on which X did not rank first.'],wordBank:['lead the table 领先','rank last 排名末位','across most measures 多数指标','variation 差异','correlation 关联','notable exception 显著例外'],example:'Overall, Canada ranked highest on all three indicators, whereas Zaire recorded the lowest figures. Income showed by far the greatest disparity, although the ranking for life expectancy and calorie supply broadly followed the same pattern.',coachNote:'Overview 的“故事”常来自列与列之间的关系，例如收入高的国家寿命也更长，而不是某个孤立数字。'},
    {label:'PARAGRAPH 03',title:'细节段一：从领先对象出发建立跨指标比较',purpose:'用少量数据证明高值组的排名和关联。',words:'50–60 words',formula:'Leading object(s) → Key values → Cross-indicator relation → Comparison',steps:['选择最能代表总体模式的两行或两列。','一句覆盖同一对象的多个相关指标。','使用 corresponding / respectively 减少重复。','不同单位只能比较排名，不能说某数字大于另一指标。'],sentenceFrames:['X recorded the highest income, at …, and also had …','The corresponding figures for Y were …','A similar ranking is evident for …','Although A exceeded B in [measure], the reverse was true for …'],wordBank:['corresponding 对应的','respectively 分别','a similar ranking 相似排名','exceed 超过','by a substantial margin 大幅领先','be associated with 与…相关'],example:'Canada reported the highest annual income, at $11,100, together with life expectancy of 76 years and the largest calorie supply. Japan followed a similar pattern for health and nutrition despite a lower income, with corresponding figures that still exceeded those of the two developing countries.',coachNote:'不要把“相关”写成“导致”。表格只能显示 association，除非题目明确提供因果信息。'},
    {label:'PARAGRAPH 04',title:'细节段二：覆盖低值组、例外和最小差距',purpose:'完成其余数据，并指出与总体模式不完全一致之处。',words:'50–60 words',formula:'Lower group → Values/range → Exception → Final contrast',steps:['合并低值或相近对象。','用 range from … to … 压缩一列。','若有例外，明确指出它在哪个指标打破排名。','以最大差距或相近项收尾。'],sentenceFrames:['At the other end of the table, …','Figures for A and B were much lower, at … and …','Values ranged from … in X to … in Y.','This was the only indicator for which the usual ranking was reversed.'],wordBank:['at the other end 另一端','lag behind 落后','range from … to … 范围为','the usual ranking 常规排名','reverse 反转','little variation 差异很小'],example:'At the other end of the table, Peru and Zaire had dramatically lower incomes and shorter life expectancy. Zaire ranked last at 47 years and also supplied the fewest calories, while Peru performed moderately better on both measures. The gap between these countries was nevertheless far narrower for health than for income.',coachNote:'细节段不要求覆盖每个格子；目标是让关键模式有足够数据证据。'},
  ],
  languageZones:[{title:'排名',note:'跨指标概括表现。',items:['lead the table in terms of …','rank first / last','perform best on most measures','lag behind the remaining countries']},{title:'对应数据',note:'减少重复。',items:['the corresponding figure for …','respectively','a similar ranking is evident','values for the same indicator']},{title:'差距与范围',note:'突出列内变化。',items:['show substantial variation','range from … to …','differ by only …','by far the widest gap']},{title:'例外与关系',note:'讲表格故事。',items:['the only measure on which …','follow the same broad pattern','show a positive association','the ranking was reversed for …']}],
  scoreFocus:task1ScoreFocus,
  pitfalls:['尝试覆盖每个单元格。','不同单位的列直接比较大小。','把相关关系写成因果。','没有 Overview，只在细节中堆数字。','行列交叉看错，数字归错对象。','只横向写对象，没有纵向比较指标模式。'],
  checklist:['开头是否概括了行、列和时间？','Overview 是否写整体领先者与主要模式？','细节段是否只选择关键单元格？','不同单位是否避免直接大小比较？','是否同时包含横向与纵向观察？','行列、单位和 respectively 顺序是否核对？'],
  drills:['用 30 秒横扫一遍、纵扫一遍，各写一个发现。','把 20 个单元格缩成 6 个关键数据。','找出表中唯一打破整体排名的指标。','练习用 corresponding / respectively 合并句子。'],
};

const processMap: GuideCourse = {
  id:'process-map', task:'task1', name:'流程 / 地图', en:'Process & Map', accent:'#cbbcff',
  promise:'流程题讲清阶段与转化，地图题讲清方位与功能变化。', duration:'20 MIN', targetWords:'170–200 WORDS',
  coreRule:'两类题都没有传统数据比较，但逻辑不同：流程题按阶段和物质变化组织，多用被动语态；地图题按空间区域和前后变化组织，多用改建、扩建与保留表达。',
  questionSignals:['The diagram shows how … is produced / recycled.','The process illustrates the stages involved in …','The maps show [place] before and after …','The plans compare the layout of … in [years].'],
  examFlow:[{time:'00–02',action:'先判流程或地图',output:'流程找起终点/阶段；地图找方向/基准物/年份。'},{time:'02–04',action:'划分两组',output:'流程分前后阶段；地图按功能区或方位分区。'},{time:'04–17',action:'按顺序成文',output:'Overview 写总体转化；细节保持时间或空间路线。'},{time:'17–20',action:'动词检查',output:'流程查被动与顺序；地图查方位、变化动词和时态。'}],
  blueprint:[{part:'P1 · Introduction',words:'25–35',job:'改写生产过程或地点/平面图变化。'},{part:'P2 · Overview',words:'35–45',job:'流程写类型、起终点和阶段；地图写总体功能转向与主要保留。'},{part:'P3 · Details 1',words:'55–65',job:'流程写前半阶段；地图写北/西/核心区或早期主要变化。'},{part:'P4 · Details 2',words:'55–65',job:'流程写后半阶段；地图写其余区域并完成前后关系。'}],
  paragraphs:[
    {label:'PARAGRAPH 01',title:'开头段：先让考官知道你面对哪一种图',purpose:'准确改写流程对象或地图地点、时间，不添加图外用途。',words:'25–35 words',formula:'Diagram/map type ＋ Subject/place ＋ Time/purpose',steps:['流程题找 produce / recycle / life cycle 的核心对象。','地图题找地点、两个时间点和 proposal / redevelopment。','保持客观，不解释为什么改造或哪个方案更好。'],sentenceFrames:['The diagram illustrates the process by which [product] is manufactured.','The figure shows the stages involved in recycling …','The maps compare the layout of [place] in [year] and at present.','The plans show how [site] is proposed to be redeveloped.'],wordBank:['manufacture 制造','stages involved in 涉及阶段','layout 布局','redevelop 重新开发','proposed 规划中的','life cycle 生命周期'],example:'The diagrams illustrate how cement is manufactured from raw materials and how the finished cement is subsequently used in the production of concrete.',coachNote:'process 用 how … is produced；map 用 how a place changed。二者句法不要混用。'},
    {label:'PARAGRAPH 02',title:'Overview：流程看转化，地图看功能',purpose:'不写细枝末节，概括全图的起终点、阶段结构或整体空间变化。',words:'35–45 words',formula:'Process: linear/cyclical + start/end + major phases · Map: overall transformation + additions/removals + retained feature',steps:['流程先判断线性、循环、自然或人工过程。','找原料输入、成品输出和关键转化点。','地图判断总体从住宅/农业转向旅游/商业等功能。','指出最大新增、拆除以及重要保留。'],sentenceFrames:['Overall, this is a linear, [number]-stage process beginning with … and ending with …','The cycle is continuous, as the final stage leads back to …','Overall, the area became more residential / accessible / recreational.','Most of the site was redeveloped, while [feature] remained intact.'],wordBank:['linear 线性的','cyclical 循环的','culminate in 最终于','undergo redevelopment 经历改造','remain intact 保持不变','be transformed into 被转变为'],example:'Overall, cement production is a linear process involving crushing, mixing, heating and grinding, whereas concrete is created in a single mixing stage from four ingredients. The finished cement forms only one component of the final concrete mixture.',coachNote:'Overview 不是重复图题。流程要写“从什么到什么”，地图要写“从何种功能变成何种功能”。'},
    {label:'PARAGRAPH 03',title:'细节段一：建立一条不会迷路的描述路线',purpose:'按前半流程或固定方位写第一组信息，保持顺序连续。',words:'55–65 words',formula:'Start point/location → Sequential changes → Intermediate stage / spatial comparison',steps:['流程用 first / once / following this 推进，并写物质状态变化。','地图先选北到南、左到右或核心到外围的一条路线。','每句让旧物与新物发生对应：was replaced by / converted into。','不要在描述中跳回已经写过的区域。'],sentenceFrames:['Initially, [materials] are fed into …','Once crushed, the material is transferred to …','In the northern part of the site, the former X was replaced by Y.','To the west of [landmark], a new … was constructed.'],wordBank:['be fed into 被送入','be transferred to 被转移到','undergo 经历','be replaced by 被取代','be converted into 被改建为','to the north of 位于…北侧'],example:'Initially, limestone and clay are passed through a crusher to form powder. This material is then mixed before entering a rotating heater, where heat is applied from one end. The heated mixture subsequently travels along a conveyor to a grinder, producing fine cement.',coachNote:'地图方位必须相对于明确基准物；流程中的 it / this material 必须让读者知道指什么。'},
    {label:'PARAGRAPH 04',title:'细节段二：完成后半阶段或剩余区域并闭环',purpose:'描述流程输出、循环返回或地图另一功能区，确保全图覆盖。',words:'55–65 words',formula:'Intermediate point → Remaining changes → Final output / retained relationship',steps:['流程继续沿箭头到最终产品，写输入比例时保持准确。','循环流程说明末端如何回到开头。','地图覆盖剩余区域，并补充道路、入口、路径等连接变化。','最后一句可对照保留项，但不写个人评价。'],sentenceFrames:['At the final stage, the material is … before being packaged.','The resulting product is then combined with … in a mixer.','Meanwhile, the southern section was converted into …','Although X was expanded, Y remained in its original position.'],wordBank:['resulting product 所得产品','be combined with 与…混合','be packaged 被包装','meanwhile 与此同时','be expanded 被扩建','retain 保留'],example:'After grinding, the cement is packaged for distribution. To produce concrete, 15% cement is added to 10% water, 25% sand and 50% gravel. These ingredients are poured into a concrete mixer, which rotates until the four materials form the finished product.',coachNote:'流程结尾要真正到达输出；地图结尾要覆盖另一半空间。不要停在中间阶段。'},
  ],
  languageZones:[{title:'流程顺序',note:'让步骤自然衔接。',items:['initially / at the outset','once this has occurred …','following this stage …','the process culminates in …']},{title:'流程被动',note:'关注动作而非执行者。',items:['be crushed / heated / filtered','be fed into / passed through','undergo treatment','be combined with …']},{title:'地图变化',note:'精准区分新增与转换。',items:['be constructed / added','be demolished / removed','be replaced by / converted into','be expanded / relocated']},{title:'方位与保留',note:'建立空间关系。',items:['to the north / south of …','in the north-eastern corner','adjacent to / opposite …','remain intact / unchanged']}],
  scoreFocus:task1ScoreFocus,
  pitfalls:['流程遗漏起点、输出或循环返回。','流程只用主动语态且主语反复是 people。','地图没有固定路线，东跳西跳。','把 replaced by 的前后对象写反。','加入图中没有的原因、好处或推测。','Overview 只说有很多变化。'],
  checklist:['我是否先判断了流程/地图的组织逻辑？','Overview 是否有起终点或总体功能变化？','流程是否覆盖所有关键阶段且顺序正确？','地图是否使用明确方位和基准物？','被动语态、变化动词和时态是否准确？','是否避免了所有图外解释和评价？'],
  drills:['为任一流程只写“起点—转化—终点”Overview。','用被动语态连续描述五个制造动作。','选择地图固定路线，用 45 秒口述全部变化。','分别练 added / replaced / converted / retained 四类地图句。'],
};

export const guideCourses: GuideCourse[] = [opinion, discussion, advantages, problem, twoPart, line, bar, pie, table, processMap];

export function getGuideCourse(id: string) {
  return guideCourses.find(course=>course.id===id);
}
